### ISSUE TITLE
Overleden persoon, maar plaats en datum van overlijden niet gekend

### ISSUE THREAD

**Issue by DieterDePaepe** [Informatievlaanderen/OSLO-Public-Discussion#10]
Originele vraag door @jdevreese:

We moeten soms data uitwisselen die niet uit authentieke bronnen zoals het rijksregister afkomstig is. Die data kan dus onvolledig zijn.

Er zijn gevallen waar we weten dat een persoon overleden is, maar waar we niet beschikken over een plaats of datum van overlijden. Hoe kunnen we in het Oslo² model voor zo'n gevallen toch aangeven dat een persoon overleden is?

**Comment by DieterDePaepe** [comment]
Een aantal opties, in volgorde van mijn voorkeur:

- We voegen een boolean attribuut `legaalOverleden` toe aan het model. Het al dan niet overleden zijn is een kern feit van een persoon, dat nog los staat van locatie of tijdstip van overlijden. Ik stel `legaalOverleden` voor tegenover `overleden` om situaties te vermijden waar het niet gekend is of een persoon overleden is, bvb voor vermiste personen. (Mijn legale kennis kan hier te kort schieten.)
- Er wordt een attribuut van buiten OSLO² gebruikt, op zich mogelijk binnen Linked Data, maar wellicht niet gewenst in de wereld van compliancy met vaste applicatie profielen.
- Als `plaatsVanOverlijden` een link is (tegenover een String), zou een blanco node hier kunnen aanduiden dat de persoon overleden is, maar dat de details niet gekend zijn.

**Comment by jdevreese** [comment]
In het datamodel van een deel van onze toepassingen, hebben we natuurlijke personen een `status`-veld gegeven. Misschien kan ook die optie overwogen worden?

Mogelijke waarden zijn bijvoorbeeld `'Normaal'`, `'Overleden'`, `'Geannuleerd dossier'`, `'Afvoering van ambtswege'`,...
(Waarden die geïnspireerd zijn op de speciale codes die gebruikt worden in [IT001](http://www.ibz.rrn.fgov.be/fileadmin/user_upload/nl/rr/instructies/IT-lijst/IT001_Gemeente_Verblijf.pdf) van het rijksregister.)

(`'Vermist'`, het voorbeeld dat je aangaf in je eerste voorstel, is in ons model nog geen mogelijke waarde voor `status`, maar het zou wel een nuttige toevoeging kunnen zijn.)

**Comment by DieterDePaepe** [comment]
Ik ben minder voorstander van een `status` veld wegens volgende redenen:
- de codes die daarin gebruikt worden, zijn erg gekoppeld zijn aan 1 enkel land
- de codes reflecteren meer de status van het Rijksregister tegenover kern data van een persoon (een `'Geannuleerd dossier'` is informatie die bij het beheer van personen hoort ipv de persoon)

**Comment by jdevreese** [comment]
Akkoord. Zaken zoals geannuleerd dossier, nis-code van gemeente/consulaat horen hier inderdaad niet thuis. Dit hoort eerder bij GeregistreerdPersoon of Inwoner, denk ik.

Het status-veld hoeft niet geïmplementeerd te worden op dezelfde manier als in IT001.
Je kan het ook algemener zien: Normaal, Overleden, Vermist/Onbekend
Laat je Vermist weg, dan kom je inderdaad op een booleaanse waarde zoals `legaalOverleden`.

**Comment by DieterDePaepe** [comment]
Wordt opgevangen in model van maart, gezien een overlijden daar een aparte entiteit is. In deze entiteit kan informatie ontbreken.
