### ISSUE TITLE
BoomVormType van BoomVorm

### ISSUE THREAD

**Issue by filipmahieu** [Informatievlaanderen/OSLO-Public-Discussion#100]
Items 'Vrij_uitgroeiend_0M', 'Vrij_uitgroeiend_3M' tem 'Vrij_uitgroeiend_9M': veranderen naar 'Vrij_uitgroeiend' tout court. Het aantal meter is niet steeds één van die aantallen of meestal niet bepaald (niet wenselijk). In ander veld eventueel te plaatsen.

**Comment by tibaert** [comment]
Zou een apart, niet verplicht, attribuut kunnen worden [BoomVormType](http://test.data.vlaanderen.be/doc/applicatieprofiel/openbaardomein#BoomVormType) VRIJ_UITGROEIND is. Al creëer je dan een attribuut dat enkel gebruik wordt indien men dit specifieke [BoomVormType](http://test.data.vlaanderen.be/doc/applicatieprofiel/openbaardomein#BoomVormType) heeft. 
Als alternatief een subtype van [BoomVorm](http://test.data.vlaanderen.be/doc/applicatieprofiel/openbaardomein#BoomVorm) creëren met als extra attribuut de takvrije stamlengte. Misschien zijn er nog specifieke eigenschappen verbonden aan de andere  [BoomVormTypes](http://test.data.vlaanderen.be/doc/applicatieprofiel/openbaardomein#BoomVormType)

**Comment by tibaert** [comment]
#81 (extra) attributen voor BoomVorm

**Comment by tibaert** [comment]
Consensus om voorstel met betrekking tot wijziging codelijst te aanvaarden.
Meerdere hoogtes kunnen van toepassing zijn voor vrij uitgroeiende bomen, bv. De actuele of gewenste hoogte. Een voorbeeld hiervan kan teruggevonden worden in het boompaspoort van Antwerpen.

**Comment by tibaert** [comment]
Opgelost tijdens Diepteoverleg Vegetatie-Element
