### ISSUE TITLE
Waterloop types inconsistent met GRB "Wgr Gracht"

### ISSUE THREAD

**Issue by jensscheerlinck** [Informatievlaanderen/OSLO-Public-Discussion#102]
https://www.agiv.be/producten/grb/objectcatalogus/entiteiten/wgr-gracht

Definitie Gracht in GRB:

> Een gracht (Wgr) is een **waterloop, een beek of een sloot**, bedoeld voor de af- of aanvoer of het tijdelijk ophouden van oppervlaktewater en gelegen binnen de wegbaan (baangrachten).

Momenteel wordt in het model voor openbaar domein volgende types van waterlopen voorzien:
- `GRACHT`: Een binnen de wegbaan gelegen onbevaarbare waterloop, bedoeld voor de af- of aanvoer of het tijdelijk ophouden van oppervlaktewater
- `SLOOT_BEEK`: Een buiten de wegbaan gelegen onbevaarbare waterloop, bedoeld voor de af- of aanvoer of het tijdelijk ophouden van oppervlaktewater
- `RIVIER_KANAAL`: Een al dan niet natuurlijke waterloop, bedoeld voor de af- of aanvoer of het tijdelijk ophouden van oppervlaktewater en die bevaarbaar is.

Waarbij `GRACHT `en `SLOOT_BEEK `afzonderlijke types zijn.
Volgens de GRB definitie zijn deze equivalent.

Verder kan het interessant zijn om RIVIER_KANAAL te aligneren met de GRB entiteit 'Watergang' (https://www.agiv.be/producten/grb/objectcatalogus/entiteiten/wtz-watergang).

Definitie Watergang:

> De watergang (Wtz) beslaat het gebied dat rechtstreeks gedomineerd wordt door de fysieke aanwezigheid van oppervlaktewater (waterlopen en stilstaande wateroppervlakken). In de praktijk benadert de watergang (Wtz) het oppervlak tussen de insteken van de beide oevertaluds (kruin).

Rivier en kanaal kunnen dan subtypes zijn van watergang met hun eigen definities.

**Comment by tibaert** [comment]
Bij [GRB-basis](https://www.agiv.be/producten/grb/objectcatalogus/componenten/grb-basis/wgr-gracht) is de definitie van Gracht minder eng: Geen vermelding van "gelegen binnen de wegbaan". 

> Een gracht is een waterloop, een beek of een sloot, bedoeld voor de af- of aanvoer of het tijdelijk ophouden van oppervlaktewater. 

Het model voor Openbaar Domein maakt een onderscheid tussen `GRACHT` en `SLOOT_BEEK` op basis van binnen en buiten de wegbaan.

**Comment by tibaert** [comment]
Voor dit model is het in principe enkel nodig om extra te definiëren wat buiten de Vlaamse Hydrografische Atlas van de Vlaamse Milieumaatschappij (VMM) valt.

Verder heeft het VMM heeft een datamodel Kube gemaakt rond waterloopbeheer (ook waterkunstwerken enz.). Bestaan Excels voor met lijsten, maar is geen open data en er is geen online documentatie van het model beschikbaar.

Link met infrastructuur elementen: bij het object Rooster bestaat momenteel geen type voor de inlaat en overloop van vijvers. Dit kan mee opgenomen worden aangezien deze ook worden ingetekend.

**Comment by jensscheerlinck** [comment]
Bestaande opdeling van waterdelen goed bevonden door de werkgroep op 17 mei: http://data.vlaanderen.be/doc/applicatieprofiel/waterdeel/
