### ISSUE TITLE
Waterzone als (beheer)gebied

### ISSUE THREAD

**Issue by JorisVerbeken** [Informatievlaanderen/OSLO-Public-Discussion#103]
Volgens ervaring GGINO-vervolgtraject Aalst (GGINO 1.1 en 1.2): waterverkeerzone werd wel gemodelleerd, maar een specifieke waterzone niet. (typisch voorbeeld: De Blaarmeersen in Gent)

Werd toegevoegd in GGINO 1.2:
-- Definition --
Zone waarin waterlopen of watervlakken gelegen zijn, inclusief de gebieden die wezenlijk deel uitmaken van deze waterlopen of watervlakken (vb: oevers)

-- Description --
NOTE GRB Lexicon: Deel van corridor
NOTE: Het is niet noodzakelijk om bij elk watervlak-beheerobject een waterzone rond te definiëren. Het is pas zinvol bij watervlakken van aanzienlijke omvang (vb: Blaarmeersen in Gent)

**Comment by tibaert** [comment]
Is Waterzone niet eerder een [BeheerDeel](http://test.data.vlaanderen.be/doc/applicatieprofiel/openbaardomein#Beheerdeel) ipv een [BeheerGebied](http://test.data.vlaanderen.be/doc/applicatieprofiel/openbaardomein#Beheergebied). 
In het voorbeeld van de Blaarmeersen, is de Blaarmeersen een recreatiezone. Dit bevat een waterzone/[waterdeel](http://test.data.vlaanderen.be/doc/applicatieprofiel/openbaardomein#Waterdeel) als [BeheerDeel](http://test.data.vlaanderen.be/doc/applicatieprofiel/openbaardomein#Beheerdeel).

**Comment by tibaert** [comment]
In welke mate is een waterloop ook een [Beheergebied](http://test.data.vlaanderen.be/doc/applicatieprofiel/openbaardomein#Beheergebied)?
Gebied dat ook de oevers en eventuele andere elementen bevat in en rond het water.

**Comment by tibaert** [comment]
Te bespreken tijdens diepteoverleg Beheergebied en eventueel Terreindeel

**Comment by jensscheerlinck** [comment]
Op basis van diepteoverleg met de werkgroep rond gebieden werd volgende lijst vastgelegd:

http://data.vlaanderen.be/doc/applicatieprofiel/gebied/#overview

Cf. http://data.vlaanderen.be/doc/applicatieprofiel/gebied/#Waterverkeerzone
