### ISSUE TITLE
Toevoeging en aanpassing (beheer)gebiedzones: Groenzone, Openbare voorzieningzone, Trage wegzone, Straatzone

### ISSUE THREAD

**Issue by JorisVerbeken** [Informatievlaanderen/OSLO-Public-Discussion#104]
Volgens ervaring GGINO-vervolgtraject Aalst (GGINO 1.1 en 1.2): aanvullingen + verbeteringen definitie van bestaande (beheer)gebiedzones: Groenzone, Openbare voorzieningzone, Trage wegzone, Straatzone

1. Groenzone:
-- Definition --
Algemene benaming voor een zone met een aanzienlijke aandeel begroeide terreindelen en/of vegetatie-elementen.
-- Description --
NOTE GRB Lexicon: Deel van surplusgebied of deel van corridor.
NOTE: In het openbaar domein bevinden zich zones die oorspronkelijk restgebieden waren, maar geëvolueerd zijn naar begroeide gebieden. Deze gebieden zijn veelal gelegen in de nabijheid van wegbanen.

2. Openbare voorzieningzone:
-- Definition --
Algemene benaming voor een zone waarin een gebouw gevestigd is dat een functie van openbare voorziening heeft.
-- Description --
NOTE GRB Lexicon: Deel van surplusgebied
NOTE: Onderscheidt zich van tuinzone door het feit dat deze zone slechts een beperkte esthetische waarde heeft.

3. Trage wegzone:
-- Definition --
Zone bedoeld om hoofdzakelijk voet- of fietsverkeer, al dan niet gecombineerd met landbouwvoertuigen, te kunnen laten plaatsvinden.
-- Description --
NOTE GRB Lexicon: Deel van surplusgebied

4. Straatzone
-- Definition --
Zone bedoeld om hoofdzakelijk motorisch verkeer te kunnen laten plaatsvinden.
-- Description --
NOTE Een straatzone draagt steeds een straatnaam (CRAB)
NOTE: Inclusief alle voetpaden, fietspaden, parkeervlakken, ...
NOTE GRB Lexicon: Deel van corridor

**Comment by tibaert** [comment]
Te bespreken tijdens diepteoverleg Beheergebied

**Comment by jensscheerlinck** [comment]
Op basis van diepteoverleg met de werkgroep rond gebieden werd volgende lijst vastgelegd:

http://data.vlaanderen.be/doc/applicatieprofiel/gebied/#overview
