### ISSUE TITLE
Verkeerseiland, Verkeersplateau, Verkeersdrempel

### ISSUE THREAD

**Issue by JorisVerbeken** [Informatievlaanderen/OSLO-Public-Discussion#105]
Volgens ervaring GGINO-vervolgtraject Aalst (GGINO 1.1 en 1.2): objecten toegevoegd en definities aangepast op vlak van Verkeerseiland, Verkeersplateau en Verkeersdrempel.

1. Verkeersdrempel:
-- Definition --
Een verkeersdrempel is een vast inrichtingselement binnen de zone voor snelverkeer van de wegbaan met als doel de normale verkeersstroom te remmen of te compartimenteren. Een verkeersdrempel is een transversaal inrichtingselement dat overwegend dwars op de hartlijn van de wegbaan georiënteerd is.
-- Description --
NOTE: Een verkeersdrempel onderscheidt zich van een verkeersplateau door de beperkte lengte (korter dan een personenwagen; cf. verkeersplateau)
NOTE Bron definitie: GRB-basis: WTI1: Verhoogde verkeersdrempel
NOTE cf. GRB Lexicon: Deel van corridor

2. Verkeerseiland:
-- Definition --
Algemene benaming voor verharde terreindelen die bedoeld zijn om het wegverkeer te sturen.
-- Description --
NOTE EXAMPLE: Verkeersgeleider, Verkeersheuvel, Vluchtheuvel
NOTE cf. GRB Lexicon: Deel van corridor

3. Verkeersplateau:
-- Definition --
Een verkeersplateau is een vast inrichtingselement binnen de zone voor snelverkeer van de wegbaan met als doel de normale verkeersstroom te remmen of te compartimenteren. Een verkeersplateau is een transversaal inrichtingselement dat overwegend dwars op de hartlijn van de wegbaan georiënteerd is.
-- Description --
NOTE: Een verkeersplateau onderscheidt zich van een verkeersdrempel door de grotere lengte (minstens gelijk aan de lengte van een personenwagen; cf. verkeersdrempel)
NOTE Bron definitie: GRB-basis: WTI1: Verhoogde verkeersdrempel
NOTE cf. GRB Lexicon: Deel van corridor

**Comment by tibaert** [comment]
Te bespreken tijdens diepteoverleg Taxonomie Terreindeel

**Comment by jensscheerlinck** [comment]
Definitie verkeersdrempel overgenomen zoals in GRB: https://test.data.vlaanderen.be/doc/applicatieprofiel/infrastructuurcataloog/#Verkeersdrempel

Verkeersplateau en verkeerseiland werden niet als eigen gebied/terreindeel/infrastructuur-element gedefinieerd maar als "collectie" van verschillende delen en elementen die samen het verkeersplateau vormen. Zie ook #122
