### ISSUE TITLE
Afbakenen van scope: datamodel openbaar domein vs wegreglement

### ISSUE THREAD

**Issue by JorisVerbeken** [Informatievlaanderen/OSLO-Public-Discussion#107]
Bij het in gebruik nemen van het datamodel in Aalst (GGINO 1.2) kwamen we op een gegeven moment tot de kwestie dat het GGINO datamodel in het vaarwater van het verkeersreglement kwamen. Typisch voorbeeld: parkeervlakken voor mindervaliden, of parkeervlakken voor garagepoorten of parkeervlakken gereguleerd door wegmarkeringen.

--> We zouden moeten kunnen afbakenen hoe ver we met het datamodel openbaar domein willen en moeten gaan.

**Comment by tibaert** [comment]
Er is interne overleg met verscheidene andere Werkgroepen die te maken hebben met het Openbaar Domein (cfr. WGS03)

**Comment by jensscheerlinck** [comment]
Alles wat met het (aanvullend) wegreglement te maken heeft valt onder de scope van de OSLO werkgroep Lokale Besluiten als Linked Open Data (LBLOD) - Mobiliteit, zie: https://lokaalbestuur.vlaanderen.be/lokale-besluiten-als-gelinkte-open-data/lblod-mobiliteit
