### ISSUE TITLE
Parkeervlak: verkeerde 'note'

### ISSUE THREAD

**Issue by JorisVerbeken** [Informatievlaanderen/OSLO-Public-Discussion#109]
Bij 'parkeervlak' hebben we in 1.0 gezegd dat dit deel uitmaakt van corridor, maar eigenlijk kan een parkeervlak zowel van de corridor als van het surplusgebied deel uitmaken.

Hieronder definitie en beschrijving van 'Parkeervlak':
-- Definition --
Gebied bestemd voor het parkeren van voertuigen.

-- Description --
NOTE cf. GRB Lexicon: Kunnen zowel deel uitmaken van corridor als van surplusgebied

**Comment by jensscheerlinck** [comment]
Aangepaste definitie zie: https://test.data.vlaanderen.be/doc/applicatieprofiel/terreindeel/#Parkeervlak
