### ISSUE TITLE
FormeelKader tegenover JuridischKader

### ISSUE THREAD

**Issue by DieterDePaepe** [Informatievlaanderen/OSLO-Public-Discussion#11]
OSLO1 heeft als concept een `JuridischKader`, terwijl ISA een `FormalFramework` refereert.

Definitie JuridischKader (uit [OSLO1.1 spec 2.6.3](https://www.v-ict-or.be/assets/5384d510ce3fb57c500006ad/OSLO1.1-specificaties.pdf))

> De machtigingen zijn afgeleid van het juridisch kader, i.e. een set van wetten, decreten en
> richtlijnen die een bepaalde dienstverlening of machtiging documenteren.
> Het juridisch kader dat hier bedoeld wordt, is specifiek in het kader van de machtigingen die
> gebruikt worden om rollen te typeren in het kader van een bepaalde dienstverlening.

Definitie FormalFramework (uit [ISA core](https://joinup.ec.europa.eu/asset/core_vocabularies/asset_release/core-vocabularies-v11#download))

> Legislation, policy, or policies lying behind the rules that govern a public service.

Beschrijving FormalFramework

> Instances of the Formal Framwork class are FRBR Expressions, i.e., concrete expressions of the more abstract concept of the piece of legislation or policy itself.
> 
> The European Council's invitation to introduce the European Legislation Identifier and portals such as legislation.gov.uk are relevant in this context. Adding '/data.xml' or /data.rdf' to any legislation URI on legislation.gov.uk will reveal how this can be done, for example http://www.legislation.gov.uk/uksi/2012/3170/contents/made{/data.rdf or /data.xml}.

Zijn deze concepten equivalent of niet? Er zijn voorbeelden nodig.
Is er een usecase met een FormeelKader dat buiten de wet staat?

[(Verderzetting van interne discussie)](https://github.com/Informatievlaanderen/OSLO/issues/10)

**Comment by KatrienDS** [comment]
Best ook bekijken hoe hier binnen LBLOD zal mee omgegaan worden.

**Comment by DieterDePaepe** [comment]
Enkel FormeelKader is behouden.
In LBLod is er opgemerkt dat de ELI ontology nog over andere begrippen spreekt (`LegalExpression`, `LegalResource`), na feedback van ons zullen ze bekijken hoe ze afstemmen met CPOV.
