### ISSUE TITLE
Lineage en historiek?

### ISSUE THREAD

**Issue by JorisVerbeken** [Informatievlaanderen/OSLO-Public-Discussion#110]
Ik lees in andere discussies binnen OSLO dat de kwestie leeft hoe we met historiek omgaan. Hier binnen OSLO - Openbaar Domein zou dit ook goed moeten worden doorbesproken. Binnen GGINO 1.2 hebben we alvast een manier geïmplementeerd die het ons mogelijk maakt om historiek bij te houden. Is te complex om in deze issuelijst neer te typen, maar ik kan gerust verduidelijken indien nodig.

**Comment by bogaerpe** [comment]
Ik ben fan!

**Comment by tibaert** [comment]
Zie [OSLO Generiek ](http://data.vlaanderen.be/doc/applicatieprofiel/generiek)
