### ISSUE TITLE
Boombeugel - Boompaal

### ISSUE THREAD

**Issue by JorisVerbeken** [Informatievlaanderen/OSLO-Public-Discussion#111]
We merken dat het nodig is om in de definities voor boombeugel en boompaal te verfijnen.
Een boombeugel is een min of meer langdurige constructie voor bescherming van een boom (vb: driehoekige structuur, blijft verschillende jaren staan) ; een boompaal doet dit ook, maar is minder langdurig en dient enkel voor de ondersteuning net na de aanplant (maximaal één jaar)

 -- Definition --
Een boombeugel is een verticale structuur die enerzijds zorgt voor een adequate bescherming van bomen tegen auto's, fietsen, bromfietsen, … en de anderzijds ook de nodige steun biedt bij het opgroeien van jonge bomen.
-- Description --
NOTE Bron definitie: naar GRB-skeletoptie groen- en begraafplaatsenbeheer: WGB: Boombeugel 

Een boompaal --> definiëren we niet in GGINO 1.2

**Comment by filipmahieu** [comment]
Moet boompaal als apart object aanzien worden? Tot nu toe de ervaring dat dit steeds en enkel bij het object 'Boom' wordt vermeld als 'Boompaal aanwezig?' (een ja/nee-veld)

**Comment by jensscheerlinck** [comment]
Aangepaste definitie meegenomen in model voor boombeugel. Boompaal momenteel niet mee opgenomen in model wegens op dit moment geen vraag naar vanuit de subgroep vegetatie. Kan tijdens publieke reviewperiode nog worden toegevoegd indien toch nodig om als attribuut op "Boomvorm" te definiëren.
