### ISSUE TITLE
Berm versus groenvoorziening

### ISSUE THREAD

**Issue by JorisVerbeken** [Informatievlaanderen/OSLO-Public-Discussion#112]
We hebben gemerkt dat we een duidelijker onderscheid nodig hadden voor een berm versus een groenvoorziening. De idee is dat een berm eerder langgerekt is, en dat een groenvoorziening eerder vierkantig, beperkt in omvang of lengte is.

**Comment by tibaert** [comment]
De berm is alleszins een onderdeel van de wegbaan. 
Verder te bespreken tijdens diepteoverleg Taxonomie Terreindeel

**Comment by jensscheerlinck** [comment]
https://test.data.vlaanderen.be/doc/applicatieprofiel/terreindeel/

Wegberm werd in de taxonomie onder de "Wegbaan" gestopt.
Groenvoorziening werd o.b.v. input van de werkgroep aangepast naar "Groenvlak", dat buiten de wegbaan gelegen kan zijn. Een groenvlak is "_een terreindeel met aangelegde en beheerde begroeiing, met een hoofdzakelijk visueel-structurerende functie_"

T.o.v. een wegberm: "_Langgerekte strook grond binnen de wegcorridor gelegen._"
