### ISSUE TITLE
Beheergebied: zone voor toekomstige ontwikkeling

### ISSUE THREAD

**Issue by JorisVerbeken** [Informatievlaanderen/OSLO-Public-Discussion#113]
Suggestie vanuit ervaringen PIVA bij andere besturen (ic. Denderleeuw); bepaalde zones hebben een tijdelijk (enkele jaren) andere hoofdfunctie. 

"Bv. een braakliggend onbegroeid perceel, van oorsprong een afgebroken hoekwoning, ligt te wachten op herbestemming. Voorlopig zetten buurtbewoners er nu  hun auto op. We inventariseren dit als ‘parkeerzone’. Als er geen beheergebiedtype bestaat in het datamodel voor het huidige gebruik, categoriseren we dit onder een bijkomend aangemaakt beheergebied ‘zone voor toekomstige ontwikkeling’ Bv "

**Comment by jensscheerlinck** [comment]
Dus in het eerste geval wordt de functie (type) van het gebied in de inventaris aangepast en in het tweede geval blijft ook het "oude" object met zijn oorspronkelijke functie bestaan in de inventaris? 

To-do: type toe te voegen aan codelijst 'Beheergebiedtype':
'zone voor toekomstige ontwikkeling'

**Comment by tibaert** [comment]
De functiewijziging zou kunnen bijgehouden worden met lineage #110 
Toekomstige zones krijgen een begindatum in de toekomst om aan te geven dat dit nog in ontwikkeling is. Eventueel ook een BeheerGebiedTypeValue "zone voor toekomstige ontwikkeling". De invulling van deze zone kan dan achterhaald worden met lineage (#110)

**Comment by tibaert** [comment]
Lineage (#110), zie [OSLO Generiek](http://data.vlaanderen.be/doc/applicatieprofiel/generiek)
Toevoegen attribuuttype te bespreken tijdens diepteoverleg Beheergebied
