### ISSUE TITLE
Klimtoestellen

### ISSUE THREAD

**Issue by JorisVerbeken** [Informatievlaanderen/OSLO-Public-Discussion#114]
Op dit moment kan geen onderscheid gemaakt worden tussen verschillende soorten klimtoestellen. Klimrek/klimtoren en klimmuur zouden algemeen voorkomen. Hier kan een algemeen type 'klimtoestel' nuttig zijn.

**Comment by tibaert** [comment]
Wordt opgelost aan de hand van een taxonomie. 
Te bespreken tijdens diepteoverleg Taxonomie Infrastructuur

**Comment by jensscheerlinck** [comment]
Codelijsten werd behouden voor het object "Speel- en sportvoorziening" op basis van ervaringen van de werkgroep en het feit dat er momenteel geen nood is aan verschillende attributen per type speel- en sporttoestel: https://test.data.vlaanderen.be/doc/applicatieprofiel/infrastructuurcataloog/#Speel-%20en%20sportvoorziening

In de codelijst werden deze extra types voorzien:
- Klimwand: Sportuitrusting bestaande uit een klimstructuur speciaal gebouwd voor dit doeleinde, met verschillende bouwkenmerken, en ontworpen voor diverse toepassingen binnen de klimsport en niet voorbehouden aan een bepaalde leeftijd. Cf. EN norm 12572-1.
- Klimrek: Een klimrek is een sport- of speeltoestel waarin geklommen kan worden.
