### ISSUE TITLE
footer openbaar domain

### ISSUE THREAD

**Issue by bertvannuffelen** [Informatievlaanderen/OSLO-Public-Discussion#117]
In het applicatieprofiel openbaar domein staat er dit:

"Een herbruikbare JSON-LD context definitie voor dit applicatieprofiel is terug te vinden op: http://data.vlaanderen.be/context/subsidie.jsonld"

suggestie :s/subsidie/openbaardomein

**Comment by jensscheerlinck** [comment]
Typo: aangepast naar http://data.vlaanderen.be/context/openbaardomein.jsonld
