### ISSUE TITLE
Naamgeving Beheergebiedtypewaarde: “zone”

### ISSUE THREAD

**Issue by tibaert** [Informatievlaanderen/OSLO-Public-Discussion#118]
Mogelijke verwarring over de naam “zone”. Een “zone” kan aanzien worden als een “deel/zone binnen het [Beheergebied](http://test.data.vlaanderen.be/doc/applicatieprofiel/openbaardomein#Beheergebied)”.
Andere voorstellen om de consistentie te bewaren voor BeheergebiedtypeWaarde? “...gebied”

#99 Naamgeving rond “Beheer” (naamgeving te gericht naar Beheer ipv Inventarisatie)

**Comment by jensscheerlinck** [comment]
Naamgeving besproken en aangepast tijdens werkgroepsessie 3 mei: https://test.data.vlaanderen.be/doc/applicatieprofiel/gebied/
