### ISSUE TITLE
Toegangspoorten als afsluiting? 

### ISSUE THREAD

**Issue by tibaert** [Informatievlaanderen/OSLO-Public-Discussion#120]
Definitie van [afsluiting](http://test.data.vlaanderen.be/doc/applicatieprofiel/openbaardomein#Afsluiting) AFS (Op het terrein ondubbelzinnig aanwijsbare en permanente verankerde scheiding), kan inconsistent zijn met de huidige afsluitingstypewaarde Slagboom en Toegangspoort.

De Slagboom is een apart object (WSB) gedefinieerd als “een afsluitingsmechanisme dat dient om controle uit te kunnen oefenen over het gebruik van een doorgang of toegang”. Objecten zoals slagboom en toegangspoort zijn in strikte geen afsluitingen omdat ze toegang kunnen verschaffen door de afsluiting. In brede zin zijn het ook afsluitingen omdat ze de toegang kunnen beperken.

Een hiërarchie kan gecreëerd worden tussen enerzijds de strikte afsluiting en anderzijds de afgesloten doorgang door de strikte afsluiting die beiden behoren tot een generiek object [Afsluiting](http://test.data.vlaanderen.be/doc/applicatieprofiel/openbaardomein#Afsluiting).

Toevoeging van Geluidsscherm #82  bij [afsluiting](http://test.data.vlaanderen.be/doc/applicatieprofiel/openbaardomein#Afsluiting)?

**Comment by jensscheerlinck** [comment]
Toegangspoorten en slagbomen opgenomen als "selectieve afsluiting" (_Op het terrein ondubbelzinnig aanwijsbare afsluiting die gebruikt kan worden om selectief en/of periodiek toegang te verlenen aan voertuigen, fietsers en/of voetgangers._), onder het generieke "afsluiting" en naast de "bestendige afsluiting" (_Op het terrein ondubbelzinnig aanwijsbare en permanent verankerde scheiding die statisch is in vorm en geen doorgang toelaat._):

Zie; https://test.data.vlaanderen.be/doc/applicatieprofiel/infrastructuurcataloog/#taxonomie
