### ISSUE TITLE
Wegelementen (Straatgoot, Boordsteen) als Beheerdeel in plaats van Beheerobject

### ISSUE THREAD

**Issue by tibaert** [Informatievlaanderen/OSLO-Public-Discussion#121]
[Straatgoot](http://test.data.vlaanderen.be/doc/applicatieprofiel/openbaardomein#Straatgoot), Boordsteen … als [Beheerdeel](http://test.data.vlaanderen.be/doc/applicatieprofiel/openbaardomein#Beheerdeel) in plaats van [Beheerobject](http://test.data.vlaanderen.be/doc/applicatieprofiel/openbaardomein#Beheerobject)
Straatgoot en Boordsteen worden door sommigen als [Beheerdeel](http://test.data.vlaanderen.be/doc/applicatieprofiel/openbaardomein#Beheerdeel) gezien omdat ze een oppervlakte innemen.
Er is discussie om dit zo op te nemen wegens het gebrek aan financiën, tijd en mankracht om zo'n gedetailleerde inventarisatie te doen van het Openbaar Domein.

Hoe ervoor zorgen dat beide implementaties mogelijk zijn?
Voorzien van generieke klassen (vb: Voetpad SL) waar de Boordsteen in vervat zit en de mogelijkheid om dit op te splitsen naar meerdere gedetailleerde klassen (vb Voetpad SS en Boordsteen). Bekijken hoe dit consistent te kunnen modelleren.

Mogelijkheid tot inventarisatie van het generiek object (vb Voetpad SL) en een vereenvoudigde gedetailleerde object (Boordsteen als lijn).

LOD #93

**Comment by tibaert** [comment]
- Het niet verplicht maken van een specifieke geometrie, maakt het mogelijk voor alle instanties om hun eigen LOD te bepalen. 
- De taxonomie voor functietype terreindeel kan hier een oplossing bieden. Wordt besproken in diepteoverleg Taxonomie Terreindeel

**Comment by jensscheerlinck** [comment]
Straatgoot, boordsteen, fietspad, e.d. opgenomen als terreindelen, zie https://test.data.vlaanderen.be/doc/applicatieprofiel/terreindeel/ onder "Wegbaan"
