### ISSUE TITLE
Verkeersborden

### ISSUE THREAD

**Issue by tibaert** [Informatievlaanderen/OSLO-Public-Discussion#123]
Geen duidelijke verwijzing naar verkeersbord in strikte zin in het gegevensmodel Openbaar Domein. Wel naar Signalisatiepaal_wegsignalisatie_algemeen en Signalisatiepaal_wegsignalisatie_openbaar_vervoer binnen [Straatmeubilair](http://test.data.vlaanderen.be/doc/applicatieprofiel/openbaardomein#Straatmeubilair)

**Comment by tibaert** [comment]
Bij signalisatiepaal van [GRB WPI11](https://www.agiv.be/~/media/agiv/producten/grb/documenten/grb-objectencatalogus/grb-skeletcomponenten/grb-detail/wpi11.pdf)

**Comment by jensscheerlinck** [comment]
Verkeersbord (http://data.vlaanderen.be/ns/openbaardomein/infrastructuurelement#Verkeersbord) werd toegevoegd. Verkeersborden kunnen al dan niet statisch of dynamisch zijn en al dan niet elektronisch. Tot de verkeersborden horen niet de verkeerslichten (signalisatie voor het oprijden van gelijkvloerse kruisingen, toegangen en dergelijke). Naar Wikidata (https://www.wikidata.org/wiki/Q170285).
