### ISSUE TITLE
Uri standaard

### ISSUE THREAD

**Issue by gezever** [Informatievlaanderen/OSLO-Public-Discussion#134]
Hoe pas ik de uri standaard toe op data die concepten en conceptschemes zijn?

http(s)://{domein}/{type}/{concept}(/{referentie})* 

Zijn al onze uri's dan van de vorm
https://id.milieuinfo.be/id/concept/concept_a
en
https://id.milieuinfo.be/id/conceptscheme/conceptscheme_a

En zitten die dan allemaal in dezelfde namespace?

**Comment by bertvannuffelen** [comment]
Dag,

voor data.vlaanderen.be hebben we gekozen voor 

https://data.vlaanderen.be/id/concept/{conceptscheme}/{conceptid}

ook jou schema is in overweging genomen, maar de kans op ongewenste clashes was te groot. Dus daarom de extra referentie-context

terloops een opmerking: je domein id.milieuinfo.be maakt eigenlijk de /id overbodig omdat je dan twee keer naar "identificator" verwijst. Als id.milieuinfo.be ook andere dingen ondersteund zoals /doc /ns en misschien nog wat extra achterground info, is het misschien beter om een meer generiek subdomein te nemen.

mvg,

Bert

**Comment by gezever** [comment]
Bert,
Door https://data.vlaanderen.be/id/concept/{conceptscheme}/{conceptid} als patroon te gebruiken wordt er afgeweken van de standaard.

**Comment by bertvannuffelen** [comment]
Waarom?
 
`https://data.vlaanderen.be/id/event/ovl/aalter/bb2a5e00-c9d1-11e2` op pagina 14 is toch ook van die vorm?

dus 

https://data.vlaanderen.be/id/concept/adresstatus/1  

mvg
Bert

**Comment by gezever** [comment]
We hebben het toch over het document over de URI-standaard, niet? Ik zie daar nergens https://data.vlaanderen.be/id/event/ovl/aalter/bb2a5e00-c9d1-11e2 op pagina 14 in staan.
http://data.vlaanderen.be/cms/VlaamseURI-StandaardVoorData_V1.0.pdf

**Comment by bertvannuffelen** [comment]
Je hebt gelijk: ik heb het voorbeeld uit de richtlijnen: http://data.vlaanderen.be/cms/URI_RichtlijnenDataVlaanderenBe_V1.pdf gehaald.

**Comment by gezever** [comment]
Dus er zijn twee versies 1.0 in omloop ...

**Comment by gezever** [comment]
Zo wordt het wel flexibeler.

**Comment by bertvannuffelen** [comment]
Het ene document is de standaard (minimaal en weinig achtergrond en stabiel), het tweede document is een AIV richtlijnen document (meer levend, met voorbeelden en implementatiekeuzes).

mvg,
Bert

**Comment by gezever** [comment]
Ok, dank je wel!
