### ISSUE TITLE
Is onderscheid (Niet)GevestigdInwoner nodig?

### ISSUE THREAD

**Issue by DieterDePaepe** [Informatievlaanderen/OSLO-Public-Discussion#2]
In het huidige voorstel van het model wordt een onderscheid gemaakt tussen:

- GevestigdInwoner: Belgen of buitenlanders die permanent in België verblijven;
- NietGevestigdInwoner: Buitenlanders die (nog) niet permanent willen of kunnen in België verblijven. Het gaat hier niet om bezoekers, maar personen die gedurende een lange periode willen verblijven. Bijvoorbeeld: EU ambtenaren, asielzoekers die nog wachten op erkenning of uitwisselingsstudenten.

Hebben we use cases waar dit onderscheid van belang is?

**Comment by liesbetd** [comment]
Is het geen risico dat je door het maken van dit onderscheid in je model voor sommige gebruikers te veel informatie weergeeft naar gelang hun finaliteit? Niet iedereen heeft immers toegang om bijvoorbeeld IT210 te zien. Door dit zo te modelleren geef je die gebruikers te veel informatie terug (die ze eigenlijk niet mogen zien).

**Comment by DieterDePaepe** [comment]
Terechte opmerking. Dit kan wellicht opgelost worden door ipv `GevestigdInwoner` of `NietGevestigdInwoner` de hogerliggende klasse terug te geven: `GeregistreerdPersoon`, maar dan zal hiermee rekening moeten gehouden worden in het definiëren van het domein/bereik van de attributen.

@liesbetd hoe wordt hier momenteel mee omgegaan? Is dit onderscheid bevat in een code velt of iets dergelijks dat dan niet mee wordt doorgegeven?

**Comment by liesbetd** [comment]
Wij hebben het onderscheid tussen geregistreerd (met persoonsnummer van RR of KSZ) en niet-geregistreerd persoon maar maken geen verdere opdeling tussen inwoners en niet-inwoners. Daarnaast gaan we het IT210, register van inschrijving, als apart element "PersonRegister" weergeven aan klanten die daar toegang toe hebben.

**Comment by bertvannuffelen** [comment]
Een meta opmerking, zonder in het onderscheid te gaan van bovenstaande definitie. Ik vraag me af of dat de discussie van deze definities (hoe relevant ook) niet een beetje filosofisch is en zonder einde is. Waarschijnlijk zijn er verschillende varianten van inwoner of niet-inwoner die afhankelijk van de persoonlijke situatie kunnen van toepassing zijn. Mijn mening is dus, kunnen we een modeleringsframework opzetten waarin een aantal veel voorkomende definities worden opgenomen en dat de minder frequente situaties ook kunnen gehanteerd worden.

In dit geval, denk ik dat het 'inwoner_zijn_van' in de eerste plaats een eigenschap is van een persoon en niet een klasse. Je wordt door een of andere administratief process toegekend als 'inwoner_zijn_van'. Klassen geven een zeer slechte uitbreidingsmethodiek. Je moet b.v. je model opnieuw gaan uitbreiden als er een nieuwe soort inwoner gedefinieerd wordt.  
De range van inwoner_zijn_van zou dan een klasse zijn met een property naar een geografische administratieve eenheid en een andere property naar de soort definitie.
