### ISSUE TITLE
BusinessEvent vs OrganisationEvent

### ISSUE THREAD

**Issue by DieterDePaepe** [Informatievlaanderen/OSLO-Public-Discussion#20]
In het huidige model worden 2 types Events gedefinieerd: `BusinessEvent` en `LifeEvent`. Deze zijn overgenomen uit CPSV-AP, waar ze dienen om de verschillende dienstverleningen te groeperen.

Tijdens de eerste publieke werkgroep kwam de vraag of een BusinessEvent in feite geen specialisatie is van een (nog niet gedefinieerde) OrganisationEvent . (Is een business een subklasse van Organisatie?)

**Comment by dhaeneth** [comment]
Theoretisch lijkt dit correct en wij kunnen dit wel binnen OSLO inbouwen, lijkt me (om het dan nadien te lanceren richting W3C). Vandaag nog niet realistisch tav. Org, maar wel OSLO:Organisatie.

**Comment by DieterDePaepe** [comment]
Ik sluit deze gezien `BusinessEvent` en `LifeEvent` wel overerven van `Event`. Er is geen nood aangetoond voor een extra niveau in te bouwen.
