### ISSUE TITLE
Beperkingen van AdresseerbaarObject

### ISSUE THREAD

**Issue by DieterDePaepe** [Informatievlaanderen/OSLO-Public-Discussion#28]
De definitie van `AdresseerbaarObject` beperkt zich blijkbaar tot Belgische adressen, met de uitzondering van postbussen. Dit betekent dat het in de context van organisaties onmogelijk is om:
- een postbus als maatschappelijke zetel te hebben
- een buitenlandse maatschappelijke zetel te hebben

**Comment by DieterDePaepe** [comment]
Dit lijkt mij een zware beperking aan de kant van het adres model. Ik ging er van uit dat dit gebaseerd was op het INSPIRE model dat juist het doel had om alle soort adressen in Europa toe te laten?

Ik stel voor dat we dit onderscheid invoeren. Grof geschetst:
- INSP-Adres heeft als subklasse AdresseerbaarObject.
- AdresseerbaarObject heeft een extra subklasse PostBus nodig.
- Org:Vestiging linkt naar INSP-Adres ipv AdresseerbaarObject.
- AdresseerbaarObject moet dan een duidelijk beschrijving krijgen dat het zich beperkt tot Belgische adressen.

**Comment by DieterDePaepe** [comment]
Even mezelf verbeteren, het is `Adres` die gebaseerd is op INSPIRE, niet `AdresseerbaarObject`.

Toch zouden volgende aanpassingen nodig zijn volgens mij:
- De vestiging waarnaar een Organisatie linkt zou een specialisatie van zowel [`org:Site`](https://www.w3.org/TR/vocab-org/#org:Site) (wat in het model `Vestiging` noemt) als van `AdresseerbaarObject` ipv een relatie `BestaatUit`.
- `AdresseerbaarObject` moet ook postbus ondersteunen.
- Ofwel moet `AdresseerbaarObject` ook buitenlandse entiteiten ondersteunen (evt zonder enige gekende identifier en details - een blank node) ofwel is er een relatie van `Vestiging` naar `Adres` nodig.

**Comment by GeertThijs** [comment]
Wordt gesloten om volgende reden: Buitenlandse adressen en postbussen worden inderdaad niet door de entiteit `BelgischAdres`gecovered. Gebruikers kunnen echter steunen op het datatype `Adresvoorstelling` dat voorzien is van velden als `postbus`en `land`. Het attribuut `postbus`is een type van `locatieaanduiding` (`postaldeliveryIdentifier`in Inspire). Entiteit 'Vestiging' kreeg intussen een attribuut 'vestigingsadres' vh type Àdresvoorstelling` zodat vestigingen ook een postbusadres en/of buitenlands adres kunnen hebben.
