### ISSUE TITLE
Rol in functie en lidmaatschap

### ISSUE THREAD

**Issue by DieterDePaepe** [Informatievlaanderen/OSLO-Public-Discussion#30]
Wat is de verhouding van `Rol` in het huidige model tegenover `Hoedanigheid` uit OSLO1? Moet dit gezien worden als subklasse van `Agent` of als link tussen `Organisation` en `Agent`?

**Comment by DieterDePaepe** [comment]
De documentatie van de termen zelf is wat dubieus, maar na heel wat zoeken heb ik een antwoord kunnen vinden waar ik zelf tevreden mee ben. Omdat de specs Engelse termen gebruiken maak ik even de vertaling:
- Oslo `Rol` = `org:Role`
- Oslo `heeftFunctie` = `org:Post`
- Oslo `isLidVan` = `org:Membership`

Volgens [een oude ORG discussie thread](https://lists.w3.org/Archives/Public/public-gld-wg/2013Feb/0073.html) (zie issue 51) was `Post` origineel een subklasse van `Organization` en bijgevolg dus ook van `Agent`. Deze link was verwijderd na protest van een lid uit de werkgroep zonder verdere discussie, ik vermoed door tijdsdruk. Ze hebben wel expliciet de [(ietwat verwarrende) uitleg](https://www.w3.org/TR/vocab-org/#org:Post) erbij gelaten dat een `Post` effectief een `org:Organization` kan zijn. Persoonlijk denk ik dat ze eigenlijk `Post` een subklasse van `Agent` hadden moeten maken in plaats van de link volledig te verwijderen.

Hierdoor denk ik dat `Post` eigenlijk overeenkomt met `Hoedanigheid` uit OSLO1. Verder denk ik dat elke `Post` ook een instantie van `Agent` zou moeten zijn.

Om dit allemaal te demonstreren in een voorbeeld: "Jan is secretaris bij AIV". Hierin zitten volgende (verschillende) concepten:
1. Jan, als levende persoon
2. De secretaris van AIV
3. AIV, als bedrijf
4. De rol "secretaris"

Dit voorbeeld zou als volgt gemodelleerd worden:
P1 is een instantie van `Persoon` met label "Jan".
O1 is een instantie van `Organisatie` met label "imec".
R1 is een instantie van `Role` met label "AIV Secretaris" (om onderscheid te maken van andere secretarissen)
P2 is een instantie van `Post` en `Agent` (`Person`?) met label "Secretaris AIV", een zogenoemde hoedanigheid.
P1 heeft een linkend attribuut met P2, `holds`, O1 heeft een link naar P2 via `hasPost` en P2 links naar R1 via `role`.

**Comment by DieterDePaepe** [comment]
[Deze mailthread](https://lists.w3.org/Archives/Public/public-gld-wg/2012Sep/0023.html) beschrijft waarom `Post` aangemaakt is.

**Comment by DieterDePaepe** [comment]
Nog [een interessante mailthread](https://lists.w3.org/Archives/Public/public-gld-comments/2014Mar/0000.html), met specifiek [een argumentatie om `Post` als `Agent` te beschouwen](https://lists.w3.org/Archives/Public/public-gld-comments/2014Mar/0011.html). Ik ga wel niet akkoord met sommige voorstellen in de thread vermeld.

**Comment by GeertThijs** [comment]
Ik vond [de oorspronkelijke issue](https://lists.w3.org/Archives/Public/public-gld-wg/2012Sep/0031.html) die geleid heeft tot het invoeren van Post bij Org.

**Comment by DieterDePaepe** [comment]
Vraag gesteld op de ORG mailinglijst of Post eigenlijk geen Agent moet zijn: https://lists.w3.org/Archives/Public/public-dwbp-comments/2017Feb/0004.html

**Comment by DieterDePaepe** [comment]
Hoedanigheid is gedefinieerd als subklasse van Agent en Post.
