### ISSUE TITLE
ContactInformatie niet geschikt voor buitenlandse eigenaars

### ISSUE THREAD

**Issue by DieterDePaepe** [Informatievlaanderen/OSLO-Public-Discussion#32]
Uit de eerste publieke werkgroep rond organisatie:

> we nemen [buitenlandse eigenaars] op onder contactinfo. Onder Adres nemen we het officiële adres op volgens de Belgische structuur. De adresvoorstelling (platte weergave) nemen we op onder contactinfo en daar volgen we een internationaal model.

Dit is echter niet toegestaan door de gebruikte vocabularia. ContactInformatie ([`ContactPoint` uit CPOV](https://joinup.ec.europa.eu/asset/cpov/asset_release/core-public-organisation-vocabulary-v100)) is enkel toegelaten om gebruikt te worden op een `PubliekeOrganisatie`, terwijl deze momenteel op het niveau van `Organisatie` wordt gebruikt. Conceptueel dient `ContactPoint` ook om een aanspreekpunt aan te duiden voor een bepaalde dienst, het dient niet gebruikt te worden voor organisationele informatie.

ORG biedt echter een uitweg via `Site` (in OSLO²: `Vestiging`) en `siteAddress`:

> Indicates an addess for the site in a suitable encoding. Use of a well known address encoding such as the vCard [vcard-rdf] vocabulary is encouraged but the range is left open to allow other encodings to be used. The address may include email, telephone, and geo-location information and is not restricted to a physical address.

**Comment by jensscheerlinck** [comment]
@DieterDePaepe is hier nog een actie rond nodig of kan deze issue gesloten worden?

**Comment by DieterDePaepe** [comment]
CPOV heeft zijn definities aangepast waardoor dit probleem niet meer van toepassing is.
