### ISSUE TITLE
Lidmaatschap of isLidVan

### ISSUE THREAD

**Issue by DieterDePaepe** [Informatievlaanderen/OSLO-Public-Discussion#33]
Het model bevat, overgenomen uit [ORG](https://www.w3.org/TR/vocab-org/), mogelijkheid om lidmaatschat aan te duiden via `IsLidVan` als ternaire relatie (`org:Membership`) ofwel via `IsLidVan` (`org:memberOf`). Bij de eerste kan extra extra informatie bijgehouden worden via extra elementen op de entiteit, bvb `Rol`. Bij de tweede wordt gewerkt via specialisaties bvb `isHoofdVan`, die verder geen extra info kunnen bevatten.

Geert stelt voor om in het OSLO profiel met de meer flexibele `Membership` te werken.

**Comment by DieterDePaepe** [comment]
Is dit een keuze die moet gemaakt worden? Beiden hebben hun voordelen en lijkt me eerder iets dat van geval tot geval moet bekeken worden.

**Comment by jensscheerlinck** [comment]
@DieterDePaepe is hier nog een actie rond nodig of kan deze issue gesloten worden?

**Comment by DieterDePaepe** [comment]
OSLO laat momenteel beiden toe.
