### ISSUE TITLE
FormeelKader verplicht in profiel?

### ISSUE THREAD

**Issue by DieterDePaepe** [Informatievlaanderen/OSLO-Public-Discussion#34]
Uit de suggesties van de publieke werkgroep van organisatie (over entiteit `Oprichting`):

> In het OSLO-profiel kunnen we dit verplicht maken voor PubliekeOrganisaties. Een publieke organisatie is pas een publieke organisatie als ze opgericht is ihkv een FormeelKader.

FormeelKader heeft echter geen invulling qua attributen. Dit is de definitie:

> This class represents the legislation, policy or policies that lie behind the rules that govern the service. As with the Rule class, the Formal Framework class is a sub class of frbr:Expression, i.e. instances of the class are concrete expressions of the more abstract concept of the piece of legislation or policy itself.

Als er geen authentieke bron is, kunnen we de aanwezigheid van een FormeelKader niet verplichten.

**Comment by jensscheerlinck** [comment]
@DieterDePaepe is hier nog een actie rond nodig of kan deze issue gesloten worden?
