### ISSUE TITLE
Geboortedatum 

### ISSUE THREAD

**Issue by KatrienLeire** [Informatievlaanderen/OSLO-Public-Discussion#35]
In het RR is "geboortedatum" geen datumveld. Geboortedatums als 00/00/2017 komen vaak voor. 
Om queries en rapportering te kunnen doen is het wel nuttig om in ons model een geboortedatum als datumveld te noteren. Wij hebben dit intern in Digipolis opgelost door de RR-geboortedatum in geval van "00" naar "01" om te zetten, maar via boolean aan te geven dat enkel het geboortejaar gekend is. Andere oplossingsmogelijkheden welkom!

**Comment by liesbetd** [comment]
Fedict heeft dit intern opgelost door een eigen date.xsd te gebruiken waarin we voor de maand en de dag ook 00 toelaten. Onze service gebruikt deze date.xsd boven xs:date. Is het toegelaten om zomaar de inhoud van het bericht te wijzigen (d.w.z. de datum te veranderen)?

**Comment by DieterDePaepe** [comment]
De property zal wellicht gebaseerd worden op ISO 8601, waar het mogelijk is een enkel een jaar voor te stellen: "2017-02-07" tegenover "2017".

**Comment by jensscheerlinck** [comment]
Opgelost in versie van model dat gepubliceerd werd op 31/03/2017.

http://data.vlaanderen.be/doc/applicatieprofiel/persoon
