### ISSUE TITLE
Datakwaliteit aanduiding

### ISSUE THREAD

**Issue by KatrienLeire** [Informatievlaanderen/OSLO-Public-Discussion#36]
Is er al iets algemeens voorzien voor de aanduiding van datakwaliteit van records? 
Bvb of ze uit een bron afkomstig zijn, zo ja welke, wanneer ze laatst geüdatet zijn uit die bron, evt ook een algemene indicatie van betrouwbaarheid,...

**Comment by nvdk** [comment]
https://www.w3.org/TR/vocab-dqv/ biedt veel mogelijkheden rond data quality

**Comment by jensscheerlinck** [comment]
+1 voor DQV 

In OSLO² wordt in het Generiek model (http://data.vlaanderen.be/doc/applicatieprofiel/generiek) wel de volgende constructie voorzien:

Een object (bv. een Persoon), wordt beschreven door een record. Langs deze weg kan zowel het tijdstip van creatie als de entiteit die het record beheert worden meegegeven (klasse HerkomstActiviteit).
