### ISSUE TITLE
Voornaam vs voornamen

### ISSUE THREAD

**Issue by KatrienLeire** [Informatievlaanderen/OSLO-Public-Discussion#38]
Is het de bedoeling om in het veld Voornaam steeds alle voornamen te vermelden, en dan in de volledige naam ook? 
Dat lijkt me in de praktijk moeilijk te hanteren. In het RR zitten alle voornamen inderdaad in 1 veld maar kunnen we dit in het model niet beter uitsplitsen?

**Comment by DieterDePaepe** [comment]
Standaard in een RDF model kan elk attribuut meerdere keren voorkomen. Zo zou een persoon dus meerdere, aparte voornamen kunnen hebben. Een zij-effect hiervan is dat deze niet gerangschikt zijn. Als er een "primaire voornaam" bestaat, zou dit toegevoegd moeten worden.

In het applicatie profiel worden er echter wel beperkingen op de cardinaliteit van elk attribuut gezet.

**Comment by jdevreese** [comment]
Misschien moet er dan een volgorde uitgedrukt kunnen worden met een volgnummer per naam/voornaam?

**Comment by jensscheerlinck** [comment]
Issue besproken door OSLO² werkgroep op 25/09:

De kardinaliteit van het attribuut "voornaam" werd reeds aangepast om de mogelijkheid te voorzien meerdere voornamen mee te geven voor een persoon. Deze voornamen zijn in principe niet geordend.

De volgorde kan blijken aan de hand van het veld "volledige naam", waar ook alle voornamen in de correct volgorde vervat zitten.

Het attribuut gebruikte voornaam kan dienen om die voornaam aan te duiden die gehanteerd wordt in bijvoorbeeld communicatie met de persoon.
