### ISSUE TITLE
Alternatieve naam

### ISSUE THREAD

**Issue by KatrienLeire** [Informatievlaanderen/OSLO-Public-Discussion#40]
zowel IT011 (pseudoniem) als IT213 (andere naam of pseudoniem), verwijzen naar het attribuut Alternatieve naam. Kan het zijn dat er meerdere waardes tegelijk moeten kunnen weggeschreven worden? Wat doen we met het concept "roepnaam" zoals in de praktijk gebruikt wordt. Moeten we dit dan ook zo kunnen kwalificeren?
Voorbeelden van roepnamen: Johanna > Jo, Louise > Wiske

**Comment by jensscheerlinck** [comment]
In het applicatieprofiel voor Persoon wordt voor alternatieve naam inderdaad een multipliciteit van 0..* voorzien, waardoor er meerdere kunnen meegegeven worden.

http://data.vlaanderen.be/doc/applicatieprofiel/persoon#Persoon

Het OSLO² generiek model voorziet ook in een datatype "ContactInfo" voorziet ook in een eigenschap "contactnaam" die kan gebruikt worden om de (roep)naam (slechts één) te bewaren die moet gebruikt worden in communicatie met de persoon. De constructie is dan: Persoon -> is te bereiken op -> ContactInfo.
