### ISSUE TITLE
Kunnen we overweg met 'composite services', bvb. ifv. bewijslast?

### ISSUE THREAD

**Issue by dhaeneth** [Informatievlaanderen/OSLO-Public-Discussion#43]
Als ik voor een bepaalde dienstverlening een bewijs moet hebben, kan er dan van daaruit een dienstverlening opgestart worden die mij dat bewijs bezorgt (composite service)?

**Comment by jensscheerlinck** [comment]
Dit kan met de relatie PubliekeDienstverlening vereist (http://purl.org/dc/terms/requires) PubliekeDienstverlening
