### ISSUE TITLE
Kunnen we in het object 'Kanaal' ook metadata meegeven mbt. de hoedanigheid?

### ISSUE THREAD

**Issue by dhaeneth** [Informatievlaanderen/OSLO-Public-Discussion#44]
Als we denken in termen van een flow waarbij data uitgewisseld wordt mbt. de hoedanigheid (Agent), kunnen we dan metadata (bvb. wie ben ik?) mee uitwisselen met bvb. kanaal- of dienstverleningsinformatie. -> is eigenlijk meer discussie voor een executiemodel van dienstverlening.

**Comment by jensscheerlinck** [comment]
Opgelost met invoering draft model transactionele dienstverlening. Wordt binnenkort gepubliceerd onder beta.data.vlaanderen.be
