### ISSUE TITLE
datamodel PERSOON

### ISSUE THREAD

**Issue by KatrienLeire** [Informatievlaanderen/OSLO-Public-Discussion#47]
Kan er ook voor een vertaling van het class diagram naar een datamodel gezorgd worden? 
Dat zal sommige relaties tussen elementen verduidelijken (kardinaliteiten, entiteit vs attribuut) en zal het ook eenvoudiger maken om in de praktijk applicaties af te toetsen aan het OSLO² model.

**Comment by DieterDePaepe** [comment]
Het UML model is bedoeld als datamodel, effectieve implementaties staan vrij om hun eigen klassen diagram te maken gebaseerd hierop.

Kardinaliteiten staan los van het vocabularium, maar worden gespecifieerd in een applicatie profiel, waar we er voor elk OSLO² domein een zullen opleveren.
