### ISSUE TITLE
Verbijfsplaats voor Inwonerschap

### ISSUE THREAD

**Issue by peterneesCS** [Informatievlaanderen/OSLO-Public-Discussion#52]
Zeker dat GeenInwoners geen een verbijfsplaats kunnen hebben? Ik denk hier aan een referentieDomicile (een geregistreerde organisatie)
ik zou verwachten dat Inwonerschap een set verblijfplaatsen heeft, en een Inwoner een Domicile heeft (Domicile als subclass van Verblijfplaats)

**Comment by jensscheerlinck** [comment]
Dit werd aangepast in de versie van 31 maart 2017: http://data.vlaanderen.be/doc/applicatieprofiel/persoon
