### ISSUE TITLE
Verenigingen

### ISSUE THREAD

**Issue by peterneesCS** [Informatievlaanderen/OSLO-Public-Discussion#55]
Verenigingen kunnen ofwel Geregistreerde als niet-geregistreerde Organisaties zijn. (Feitelijke vereniging of met Rechtspersoon). Nu kan je Verenigingen niet 'pakken' in het model.
Suggestie: nieuwe expliciete entiteit Vereniging, met associate naar een Formele organisatie.

**Comment by jensscheerlinck** [comment]
Kan dit opgevangen worden met de eigenschap classificatie type OrganisatieClassificatie?
@DieterDePaepe @GeertThijs @rafbuyle

**Comment by DieterDePaepe** [comment]
Als vereniging een duidelijke definitie heeft, zou het daarin passen. Het feit dat er zowel geregistreerde als niet geregistreerde verenigingen zijn, doet me vermoeden dat er niet zo'n harde grens is.

**Comment by jensscheerlinck** [comment]
Issue besproken door OSLO² werkgroep op 25/09:

Feitelijke verenigingen vallen onder de klasse "Formele Organisatie".

Achtergrond: een feitelijke vereniging is erkend onder de Belgische wetgeving. Ookal worden hier geen gegevens van bijgehouden door een publieke administratie, heeft deze vereniging toch bepaalde rechten en plichten, zoals het aanvragen van bepaalde subsidies. [Dit is in lijn met de definitie van Formele Organisatie, overgenomen van de Org Ontology](https://www.w3.org/TR/vocab-org/#class-formalorganization).
