### ISSUE TITLE
CPOV: nut van next en prev

### ISSUE THREAD

**Issue by DieterDePaepe** [Informatievlaanderen/OSLO-Public-Discussion#59]
In het huidige schema hebben we de in CPOV vermelde PubliekeOrganisatie:prev en PubliekeOrganisatie:next (`http://www.w3.org/1999/xhtml/vocab#next` en `http://www.w3.org/1999/xhtml/vocab#next`) weggelaten, omdat het nut ervan onduidelijk was en de semantiek context afhankelijk.

Deze termen zijn ingevoerd tussen draft 2 en 3 van CPOV, maar we vonden geen redenering waarom in de issues of mailinglijst van CPOV.

Het nut van deze zal nog moeten achterhaald worden, en indien geldig moeten deze nog toegevoegd worden aan onze vocabularia/profielen.

**Comment by jensscheerlinck** [comment]
Uit de CPOV ontology:

> In some cases, it is necessary to be able to create an ordered sequence of organizations that precede and succeed each other. To support this, the CPOV includes the well-known relationships of previous and next to allow such sequences to be captured and computed.

**Comment by DieterDePaepe** [comment]
Ja, maar over welke volgorde gaat het? Datum van oprichting, alfabetisch op naam, volgorde zoals in de DB?

Zonder het expliciet te maken waar de volgorde voor staat, lijken deze me nutteloos.

**Comment by jensscheerlinck** [comment]
Het gebruik van de termen precedence en succession doet mij vermoeden dat het hier gaat over de fusie/reorganisatie/opsplitsing van organisaties.

Bv. organisatie A wordt overgenomen door organisatie B, ze gaan verder onder een nieuwe entiteit organisatie C, dan heb je het volgende:

C prev A
C prev B
A next C
B next C

Ik kan dit even valideren met de CPOV werkgroep.

**Comment by DieterDePaepe** [comment]
> Ik kan dit even valideren met de CPOV werkgroep.

+1

> Het gebruik van de termen precedence en succession doet mij vermoeden dat het hier gaat over de fusie/reorganisatie/opsplitsing van organisaties.

Dan zou ik verwachten dat dit al kan afgeleid worden uit de events die gekoppeld zijn aan de organisaties.

**Comment by jensscheerlinck** [comment]
Issue besproken door OSLO² werkgroep op 25/09:

Niet opnemen in OSLO² model: reeds verder uitgesplitst aan de hand van "Veranderingsgebeurtenis".
