### ISSUE TITLE
Burgerlijke staat: wettelijk samenwonen

### ISSUE THREAD

**Issue by DieterDePaepe** [Informatievlaanderen/OSLO-Public-Discussion#6]
In het huidige model voorstel is wettelijk samenwonen mee opgenomen in de burgerlijke staat. In België is dit echter geen officiële burgerlijke staat (dit telt als "ongehuwd"), in andere landen mogelijks wel. Conceptueel zijn termijn echter heel gelijkend.

- Is wettelijk samenwonen relevant voor onze use cases?
- Hoe modelleren we wettelijk samenwonen? Apart (juridische grens) of samen (inhoudelijke gelijkenis)?

**Comment by liesbetd** [comment]
Ik zou adviseren om deze begrippen gescheiden te houden in het datamodel. Semantisch betekenen ze immers absoluut niet hetzelfde in België dus lijkt het onjuist om dit onder één noemer te modelleren. Door dit onderscheid niet duidelijk in het model te verwerken, riskeer je dat het datamodel onbruikbaar wordt voor heel wat locale toepassingen.

**Comment by DieterDePaepe** [comment]
Huidige model beperkt zich tot Belgische burgerlijke staten. Het wettelijk samenwonen moet wel nog geverifieerd worden als usecase. Ik voeg dit issue samen naar #5.
