### ISSUE TITLE
"Abstracte" klasse huwelijk?

### ISSUE THREAD

**Issue by philipperutten** [Informatievlaanderen/OSLO-Public-Discussion#63]
Huwelijk : “door burgerlijk of religieus recht…”.

Is het niet juist belangrijk om ondubbelzinnig aan te geven waar het om gaat, dus OFWEL burgerlijk, OFWEL religieus — en in deze context dus waarschijnlijk burgerlijk?

**Comment by jensscheerlinck** [comment]
Issue besproken door OSLO² werkgroep op 14/09:

In België zijn beiden mogelijk, met deze klasse Huwelijk kan geen onderscheid gemaakt worden.
Of het huwelijk onder burgerlijk recht valt blijkt uit de Burgerlijke Staat van de persoon.
