### ISSUE TITLE
Klasse "geen inwoner" ?

### ISSUE THREAD

**Issue by philipperutten** [Informatievlaanderen/OSLO-Public-Discussion#65]
In welke zin is "geen inwoner" een klasse?

**Comment by DieterDePaepe** [comment]
Het is een vorm van `Inwonerschap`: iets dat een persoon aan een jurisdictie koppelt. Dit is vergelijkbaar met de `Membership` klasse uit het Organisation core vocabulary.

Er is gekozen voor een klasse tegenover een gespecialiseerde relatie, omdat er zo nog extra attributen zouden kunnen bijgehouden worden.

**Comment by philipperutten** [comment]
Ik neem aan dat je dan deze klasse bedoelt:
https://www.w3.org/TR/vocab-org/#class-membership

En die analogie begrijp ik wel voor "Inwonerschap", maar voor de negatieve variant "geen inwoner" zie ik niet direct een equivalent. 

Kun je een voorbeeld geven hoe dit gebruikt zal worden?

**Comment by DieterDePaepe** [comment]
Zelfverzonnen voorbeeld (mogelijks niet consistent met hoe de overheid persoondata bijhoudt):

Een persoon heeft asiel aangevraagd, momenteel is hij dus geregistreerd, maar is hij nog geen geldig inwoner van België.  Op datum X wordt zijn aanvraag goedgekeurd en is hij geregistreerd als inwoner.

```
:bob :heeftInwonerschap :geenInwoner.
:geenInwoner a :GeenInwoner.
:geenInwoner :inwonerschap.binnen :Belgie.
:geenInwoner :heeftVerblijfplaats :adres-asielcentrum.
:geenInwoner :validTo "2017-09-13"^^xsd:date.

:bob :heeftInwonerschap :inwoner.
:inwoner a :PermanentInwoner.
:inwoner :inwonerschap.binnen :Belgie.
:inwoner :heeftVerblijfplaats :adres-bob.
:inwoner :validFrom "2017-09-14"^^xsd:date.
```

**Comment by jensscheerlinck** [comment]
Issue besproken door OSLO² werkgroep op 14/09:

Voorbeelden van use cases waar deze klasse in praktijk nodig is:
- Grensarbeiders die geregistreerd zijn in België maar in een ander land wonen.
- Geradieerden
