### ISSUE TITLE
OSLO² Dienst: nieuw attribuut voor inverse van "heeftVerantwoordelijke"

### ISSUE THREAD

**Issue by jensscheerlinck** [Informatievlaanderen/OSLO-Public-Discussion#66]
In de context van de Notificatiecomponent is het nodige om een relatie te kunnen leggen vanuit een Publieke Organisatie naar de Publieke Dienstverlening waar deze verantwoordelijk voor is.

Momenteel is in het vocabularium Dienst (en in CPSV-AP) geen inverse relatie gedefinieerd van "heeftVerantwoordelijk" (cpsv:hasCompetentAuthority).

Voorstel om deze relatie te definiëren als "isVerantwoordelijkVoor":
```
<http://data.vlaanderen.be/ns/dienst#isVerantwoordelijkVoor>
      a       owl:ObjectProperty ;
      rdfs:isDefinedBy <http://data.vlaanderen.be/ns/dienst> ;
      owl:inverseOf <http://data.europa.eu/m8g/hasCompetentAuthority> ;
      rdfs:label "is verantwoordelijk voor"@nl ;
      rdfs:comment "Verwijst naar de Publieke Dienstverlening waar de Publieke Organisatie verantwoordelijk voor is."@nl ;
      rdfs:domain <http://data.europa.eu/m8g/PublicOrganisation> ;
      rdfs:range <http://purl.org/vocab/cpsv#PublicService> .
```

**Comment by DieterDePaepe** [comment]
Kan je wat context geven waarom deze inverse relatie nodig is? (Heeft dit te maken met JSON-LD serializatie?)

Ik vermoed dat de definitie een copy-paste foutje bevat?

**Comment by jensscheerlinck** [comment]
Definitie was inderdaad een copy-paste fout. 

In de context van de notificatiecomponent van AIV moet voor een deeltje configuratie een Publieke Organisatie aangeven voor welke Publieke Dienstverlening ze verantwoordelijk is. Om de JSON-LD structuur wat logisch te houden willen we daarom graag het volgende kunnen definiëren:

```
"@context": "http://data.vlaanderen.be/context/dienst.jsonld",
"@id": "http://example.org/aiv",
"@type": "PubliekeOrganisatie",
"isVerantwoordelijkVoor": "http://example.org/dienstverlening1"
```

We kunnen dit opvangen enkel in de context file voor dienstverlening als volgt:
`"isVerantwoordelijkVoor": { "@reverse": "http://data.europa.eu/m8g/hasCompetentAuthority" }`

Het lijkt mij nuttig moest deze info ook rechtstreeks in het vocabularium vervat zitten.
Bij nader inzien lijkt het definiëren van een nieuw attribuut zoals in de originele post misschien niet de meest elegante manier. Een alternatief is het volgende toevoegen (lijn 2):

```
eu:hasCompetentAuthority rdfs:label "heeft verantwoordelijke autoriteit"@nl .
eu:hasCompetentAuthority owl:inverseOf [ rdfs:label "is verantwoordelijk voor" ] .
```

**Comment by DieterDePaepe** [comment]
Blank nodes zijn best zo veel mogelijk te vermijden in mijn mening.

Voorlopig ben ik geen tegenstander van een extra relatie. Maar nog niet overtuigd van de nood eraan gezien het reeds uitdrukbaar is in JSON-LD. Gaat het enkel om het label van de omgekeerde relatie (dit leid ik af uit je alternatief). Zoja, maakt het toch niet uit voor JSON-LD, er is op zich geen link tussen de JSON-keys en de vocabulary termen toch? (Ook al probeert men deze wel gelijk te houden in praktijk voor menselijk begrip.)

**Comment by jensscheerlinck** [comment]
Issue besproken door OSLO² werkgroep op 14/09:

Relatie zal worden toegevoegd aan het model voor Notificatie.
