### ISSUE TITLE
Toevoeging: graf/colombarium

### ISSUE THREAD

**Issue by jensscheerlinck** [Informatievlaanderen/OSLO-Public-Discussion#73]
Werd in het ganse GGINO-traject niet aangehaald. Waarschijnlijk door de specificiteit; Wordt tijdens dit GGINO-traject niet meer verder behandeld, maar ervaringen Stad Aalst zullen  indien gewenst wel worden gedeeld.

Conclusie: begraafplaatsen nog te modelleren

**Comment by annetom** [comment]
zie GRB-skeletoptie groen- begraafplaatsenbeheer

**Comment by KristoffJanssens** [comment]
Vanuit de Stad Antwerpen willen we graag de begraafplaatsen mee integreren. Er zullen verschillende objecten of informatielagen eigen zijn aan zulke locaties. Wordt vervolgd.

**Comment by JorisVerbeken** [comment]
Graf en columbarium werd niet meegenomen in GGINO 1.0. Achteraf kwam vanuit verschillende besturen de (terechte) opmerking dat dit type objecten er ook bij hoorde. Echter zoals Jens ook reeds vermeldde: graven en columbaria zijn zodanig specifiek dat het niet problematisch is om dit type al dan niet gemodelleerd te hebben.

**Comment by tibaert** [comment]
Besproken tijdens Diepteoverleg Begraafplaatsbeheer en zal worden opgenomen.
