### ISSUE TITLE
Onderscheid tussen "parkeerplaats afgebakend door markeringen" en "indicatieve parkeerplaatsen"

### ISSUE THREAD

**Issue by jensscheerlinck** [Informatievlaanderen/OSLO-Public-Discussion#74]
Onderscheid tussen "parkeerplaats afgebakend door markeringen" en "indicatieve parkeerplaatsen" ontbreekt momenteel.

**Comment by tibaert** [comment]
Cfr. #76 en #83

**Comment by JorisVerbeken** [comment]
Volgens ervaring GGINO-vervolgtraject Aalst (GGINO 1.1 en 1.2):  onderscheid tussen "parkeerplaats afgebakend door markeringen" en "indicatieve parkeerplaatsen" zou inderdaad nuttig zijn.

**Comment by tibaert** [comment]
Te bespreken tijdens diepteoverleg Taxonomie Infrastructuur & Terreindeel

**Comment by jensscheerlinck** [comment]
Cf #76 en #83
