### ISSUE TITLE
Verfijning parkeervlakken

### ISSUE THREAD

**Issue by jensscheerlinck** [Informatievlaanderen/OSLO-Public-Discussion#76]
Parkeervlakken nog verfijnen naar vb parkeervlakken voor mindervaliden, of parkeervlakken voor garagepoorten of parkeervlakken gereguleerd door wegmarkeringen.

**Comment by jensscheerlinck** [comment]
Momenteel wordt in het model het volgende voorzien m.b.t. parkeren:

- [Parkeerzone](http://test.data.vlaanderen.be/doc/applicatieprofiel/openbaardomein#BeheerGebiedTypeValue%3APARKEERZONE) (een type [BeheerGebied](http://test.data.vlaanderen.be/ns/openbaardomein#BeheerGebied))
- [Parkeervlak](http://test.data.vlaanderen.be/doc/applicatieprofiel/openbaardomein#TerreinDeelTypeValue%3APARKEERVLAK) (een type [TerreinDeel](http://test.data.vlaanderen.be/ns/openbaardomein#TerreinDeel))


Tijdens werkgroepsessie 1 werd ook het idee geopperd om dit uit te breiden met parkeerplaatsen voor gehandicapten, parkeerstroken, ...

**Comment by tibaert** [comment]
In welke mate zijn parkeervlakken gerelateerd tot wegbelijning. Cfr. [GRB-skeletoptie wegbeheer](https://www.agiv.be/~/media/agiv/producten/grb/documenten/grb-skelet/technischebepalingengrbskeletoptiewegbeheerversie10.pdf): (Lijnvormige) wegmarkering

**Comment by tibaert** [comment]
Te bespreken tijdens diepteoverleg Taxonomie Infrastructuur (& Terreindeel)

**Comment by jensscheerlinck** [comment]
Onderscheid gemaakt tussen:
- Terreindeel "[Parkeervlak](http://data.vlaanderen.be/doc/applicatieprofiel/terreindeel/#Parkeervlak)": Vlak bestemd voor het parkeren van voertuigen. Hiermee wordt het terreindeel aangeduid waarom een voertuig kan parkeren. Een parkeervlak kan een plaats bieden aan meerdere voertuigen (bijvoorbeeld een parkeerstrook langs de kant van de weg). 

Individuele parkeerplaatsen kunnen aangeduid worden door bovenop het terreindeel parkeervlak, wegmarkering aan te brengen. Zie: https://test.data.vlaanderen.be/doc/applicatieprofiel/infrastructuurcataloog/#Lijnvormige%20wegmarkering

Momenteel geen specialisaties opgenomen voor mindervaliden, autodelen, etc. 
Zaken die bepaald worden door het (aanvullend) wegreglement, zullen gecapteerd worden in het traject [LBLOD Mobiliteit](https://lokaalbestuur.vlaanderen.be/lokale-besluiten-als-gelinkte-open-data/lblod-mobiliteit), met verwijzing naar de objecten op het openbaar domein zoals hier gedefinieerd.
