### ISSUE TITLE
Toevoegen van metadata voor bijhouden van kwaliteitsparameters

### ISSUE THREAD

**Issue by jensscheerlinck** [Informatievlaanderen/OSLO-Public-Discussion#77]
Momenteel wordt informatie zoals bv. 'conditie' enkel meegegeven bij enkele objecten, zoals een [BoomVorm](http://test.data.vlaanderen.be/doc/applicatieprofiel/openbaardomein#BoomVorm).

Uit de brainstormsessie is gebleken dat een algemeen attribuut met betrekking tot de "staat" van een object nuttig kan zijn in meerdere domeinen (ook infrastructuur gerelateerde objecten).

Voorstel om generiek attribuut ("staat" of "conditie") toe te voegen op niveau van een generiek "BeheersObject". Codelijsten kunnen gespecificeerd worden op specifiek object.

**Comment by JorisVerbeken** [comment]
Volgens ervaring GGINO-vervolgtraject Aalst (GGINO 1.1 en 1.2): wij hebben "conditie" eruit gelaten, aangezien dit eerder bij inspecties thuishoort, en relatief veranderlijk kan zijn. Maar het kan wel nuttig zijn om dit opnieuw toe te voegen, maar moet de lijn dan niet doorgetrokken worden naar alle objecten?

**Comment by tibaert** [comment]
Besproken tijdens diepteoverleg Vegetatie-element en Boomvorm
