### ISSUE TITLE
Bijhouden van metadata met betrekking tot update frequentie van de data?

### ISSUE THREAD

**Issue by jensscheerlinck** [Informatievlaanderen/OSLO-Public-Discussion#78]
Is hier nood aan in het model en welke attributen zijn hier voor nodig?
Volstaat een generiek attribuut voor update frequentie? 

Wat met andere vormen van frequenties? Zoals bv. de frequentie waarmee een vuilbak wordt geleegd.

**Comment by tibaert** [comment]
Extern op het model. Buiten scope Gegevensmodel
