### ISSUE TITLE
Wie is de "beheerder" van een object in het Openbaar Domein? 

### ISSUE THREAD

**Issue by jensscheerlinck** [Informatievlaanderen/OSLO-Public-Discussion#79]
De huidige versie van het model voorziet een "beheerder" op zowel gebied als object niveau.

Wat is de invulling van beheerder?

- Is dit telkens de gemeente?
- Kan dit een specifieke dienst zijn van een gemeente?
- Kan dit een externe (private) partij zijn die in onderaanneming het onderhoud uitvoert?

Wat met andere "actoren"? Zoals personen of organisaties verantwoordelijk voor:
- Inventarisatie
- Onderhoud
- Kwaliteitszorg

**Comment by JorisVerbeken** [comment]
De opmerking van Jens hier is zeer terecht. We hebben dit in GGINO 1.2 verfijnd: op beheergebied-niveau beschouwen we de beheerder effectief als de eigenaar. En de beheerders van de objecten die binnen deze gebieden moeten worden 'beheerd' kunnen evengoed andere organisaties zijn dan de eigenaar.

We beschouwen de 2 soorten beheerders dan als volgt:
beheergebied --> beheerder = "eigenaar"
beheerobject --> beheerder = "onderhoud-organisatie"

**Comment by tibaert** [comment]
[Beheergebied](http://test.data.vlaanderen.be/ns/openbaardomein#Beheergebied) en [Beheerobject](http://test.data.vlaanderen.be/ns/openbaardomein#Beheerobject) kunnen als eigenschap een [beheerder](http://test.data.vlaanderen.be/ns/openbaardomein#beheerder) hebben. Deze [beheerder](http://test.data.vlaanderen.be/ns/openbaardomein#beheerder) is een [Organisatie](http://test.data.vlaanderen.be/doc/applicatieprofiel/openbaardomein#Organisatie). De invulling van deze [organisatie](http://test.data.vlaanderen.be/doc/applicatieprofiel/openbaardomein#Organisatie) kan verschillend zijn naargelang het een [Beheergebied](http://test.data.vlaanderen.be/ns/openbaardomein#Beheergebied) of een [Beheerobject](http://test.data.vlaanderen.be/ns/openbaardomein#Beheerobject) is. In het huidige gegevensmodel Openbaar Domein dat wordt gebruikt door Stad Aalst, hoort bij het [Beheergebied](http://test.data.vlaanderen.be/ns/openbaardomein#Beheergebied) de eigenaar van het [Beheergebied](http://test.data.vlaanderen.be/ns/openbaardomein#Beheergebied) en bij het [Beheerobject](http://test.data.vlaanderen.be/ns/openbaardomein#Beheerobject) is het de effectieve [beheerder](http://test.data.vlaanderen.be/doc/applicatieprofiel/openbaardomein#Beheergebied%3Abeheerder) van het [Beheerobject](http://test.data.vlaanderen.be/ns/openbaardomein#Beheerobject). (Zie opmerking Joris.)
Bij een klasse kan men [Organisaties](http://test.data.vlaanderen.be/doc/applicatieprofiel/openbaardomein#Organisatie) toewijzen die een relatie hebben als Eigenaar, [Beheerder](http://test.data.vlaanderen.be/doc/applicatieprofiel/openbaardomein#Beheergebied%3Abeheerder) of Uitvoerder. De [beheerder](http://test.data.vlaanderen.be/doc/applicatieprofiel/openbaardomein#Beheergebied%3Abeheerder) is ook van toepassing op twee zaken: de beheerder van de data en de [beheerder](http://test.data.vlaanderen.be/doc/applicatieprofiel/openbaardomein#Beheergebied%3Abeheerder) van het object. Tussen de twee moet er een duidelijk onderscheid gemaakt worden binnen de definities van het gegevensmodel.

**Comment by jensscheerlinck** [comment]
Twee relaties voorzien op niveau van Gebied en Object:

- [Beheerder](http://data.vlaanderen.be/ns/openbaardomein#beheerder): Instantie (tot op team- of dienstniveau) die instaat voor het beheer van het object.
- [Eigenaar](http://data.vlaanderen.be/ns/openbaardomein#eigenaar): De entiteit (bv. de gemeente) die eigenaar is van het object.
