### ISSUE TITLE
Rijksregister-elementen out of scope

### ISSUE THREAD

**Issue by DieterDePaepe** [Informatievlaanderen/OSLO-Public-Discussion#8]
[Dit document](http://informatievlaanderen.github.io/OSLO/assets/personen/2017-01-12/DraftOSLO2Persoon_v2.pdf) geeft een overzicht van welke termen uit het rijksregister in/out scope zijn voor OSLO².

Termen die toch in scope horen te komen, kunnen hier besproken worden.

**Comment by liesbetd** [comment]
Bij IT 100 en IT 150 is ook het tijdstip van geboorte en tijdstip van overlijden beschikbaar. Het kan nuttig zijn om dit toe te voegen.

IT 250 biedt Fedict in een volgende release wel aan want daar is veel vraag naar bij onze klanten.
Een voorbeeld van een use case voor IT250:

Een persoon registreert een testament waarin hij een aantal erfgenamen definieert. Deze erfgenamen worden (verplicht) geidentificeerd aan de hand van hun persoonsnummer. 1 van de erfgenamen krijgt later een nieuw persoonsnummer (vb. geslachtsverandering). Wanneer de opsteller van het testament komt te overlijden, moet de notaris de link kunnen zien tussen de persoon die zegt dat hij de erfgenaam is en het oude persoonsnummer van die persoon.
