### ISSUE TITLE
Use case rond boombescherming en extra attibuten die hiervoor nodig zijn

### ISSUE THREAD

**Issue by jensscheerlinck** [Informatievlaanderen/OSLO-Public-Discussion#80]
In de context van boombescherming kunnen voor het object [BoomVorm](http://test.data.vlaanderen.be/doc/applicatieprofiel/openbaardomein#BoomVorm) een aantal extra attributen worden toegevoegd, zoals:

- **Markant element**, mogelijke waarden:
    - Monumentaal/Erfgoed
    - Veteraan
    - Herdenkingsboom
    - Geboorteboom
    - ...
- **Ecologische waarde**, mogelijke waarden:
    - Houdt vleermuizen
    - Nest roofvogel
    - Ectomycorrhizal symbiont 
    - Bijzondere flora
    -...

Hoort dit bij het basis model voor Openbaar Domein of een extensie specifiek rond groenbeheer?

**Comment by tibaert** [comment]
- Definities voor markante elementen voorzien door Agentschap Natuur en Bos. 
- Focus op inventarisatie, niet op geplande zaken: bosplannen niet opnemen in het gegevensmodel 
- Lineage fysiek object: 
  - Verschillende objecten met aparte begin- en einddatums
  - Meerdere Visual Tree Assessment (VTA) inspecties aan zelfde object met geometrie hangen (aparte documenten/fiches die verwijzen naar het ene object).

**Comment by tibaert** [comment]
Besproken tijdens het diepteoverleg Vegetatie-element en Boomvorm
