### ISSUE TITLE
Extra attributen voor BoomVorm in functie van boombeheer/bomenplan

### ISSUE THREAD

**Issue by jensscheerlinck** [Informatievlaanderen/OSLO-Public-Discussion#81]
In de context van boombeheer kunnen voor het object [BoomVorm](http://test.data.vlaanderen.be/doc/applicatieprofiel/openbaardomein#BoomVorm) een aantal extra attributen worden toegevoegd, zoals:

- Gebreken
- Onderhoudsplan

Hoort dit bij het basis model voor Openbaar Domein of een extensie specifiek rond groenbeheer?

**Comment by filipmahieu** [comment]
- Gebreken en onderhoudsplan is eerder bij beheer, niet bij de Boomvorm zelf vind ik.
Andere voorstel voor attribuut: 
- Standplaats: Solitair, Bomenrij, Bos

**Comment by tibaert** [comment]
In welke mate behoren deze elementen tot het [VegetatieElement](http://test.data.vlaanderen.be/doc/applicatieprofiel/openbaardomein#VegetatieElement) #90

**Comment by tibaert** [comment]
Zie ook #80 voor extra attributen voor [BoomVorm](http://test.data.vlaanderen.be/doc/applicatieprofiel/openbaardomein#BoomVorm) (Markant element, ecologische waarde)

**Comment by tibaert** [comment]
Wat betreft de aard of plaats van de boom bestaat er discussie over het al dan niet opnemen van een expliciet attribuut dat de relatie uitdrukt (een boom staat in een bos, een bomenrij of solitair). Deze relatie kan ook ruimtelijk worden uitgedrukt (een object voor een boom bevindt zich in een [terreindeel](http://test.data.vlaanderen.be/doc/applicatieprofiel/openbaardomein#Terreindeel) of [beheergebied](http://test.data.vlaanderen.be/doc/applicatieprofiel/openbaardomein#Beheergebied) voor bos), bv. Een [Boomvorm](http://test.data.vlaanderen.be/doc/applicatieprofiel/openbaardomein#Boomvorm) staat in een [Terreindeel](http://test.data.vlaanderen.be/doc/applicatieprofiel/openbaardomein#Terreindeel) met type ‘ecologische ruimte’ en een begroeid voorkomen ‘Boomvoorkomen’.

**Comment by tibaert** [comment]
Besproken tijdens diepteoverleg Vegetatie-element en Boomvorm
