### ISSUE TITLE
Geluidswering

### ISSUE THREAD

**Issue by jensscheerlinck** [Informatievlaanderen/OSLO-Public-Discussion#82]
Geluidswering ontbreekt momenteel in het model.

Geluidswering zou in het model onder "BeheerElement > InfrastructuurElement > [Afsluiting](http://test.data.vlaanderen.be/ns/openbaardomein#Afsluiting)" één van de [mogelijke types](http://test.data.vlaanderen.be/ns/openbaardomein#AfsluitingTypeValue) kunnen zijn.

**Comment by annetom** [comment]
zit in de GRB-skeletoptie wegbeheer

**Comment by tibaert** [comment]
Gedefinieerd als **geluidsscherm**: geluidswerende wand langs autosnelwegen, spoorwegen,… met als doel de omwonenden tegen geluidshinder te beschermen (3.2.8 WGS: geluidsscherm)

[GRB-skeletoptie wegbeheer](https://overheid.vlaanderen.be/GRB-skeletoptie-wegbeheer-nieuwe-specs)

**Comment by tibaert** [comment]
Te bespreken tijdens diepteoverleg Taxonomie Infrastructuur

**Comment by jensscheerlinck** [comment]
Opgenomen conform GRB: https://test.data.vlaanderen.be/doc/applicatieprofiel/infrastructuurcataloog/#Geluidscherm
