### ISSUE TITLE
(Weg)belijning in het openbaar domein (parkeervakken, sportvelden, ...)

### ISSUE THREAD

**Issue by jensscheerlinck** [Informatievlaanderen/OSLO-Public-Discussion#83]
(Weg)belijning ontbreekt momenteel in het model.

Wegbelijning zou in het model onder `BeheerElement > InfrastructuurElement` een extra object kunnen zijn, met types analoog aan die gedefinieerd in GRB optie wegbeheer (belijning).

**Comment by tibaert** [comment]
Voor wegbelijning: cfr. [GRB-skeletoptie wegbeheer](https://www.agiv.be/~/media/agiv/producten/grb/documenten/grb-skelet/technischebepalingengrbskeletoptiewegbeheerversie10.pdf): (Lijnvormige) wegmarkering 
Voor parkeervlakken: zie #76

**Comment by tibaert** [comment]
Te bespreken tijdens diepteoverleg Infrastructuur

**Comment by jensscheerlinck** [comment]
Opgenomen conform GRB: 
Wegmarkering
- Vlakvormige wegmarkering
- Lijnvormige wegmarkering
- Puntvormige wegmarkering

Onder `Signalisatie > Wegsingalisatie`

Zie https://test.data.vlaanderen.be/doc/applicatieprofiel/infrastructuurcataloog/#taxonomie
