### ISSUE TITLE
Extra attributen voor SpeelEnSportVoorziening

### ISSUE THREAD

**Issue by jensscheerlinck** [Informatievlaanderen/OSLO-Public-Discussion#84]
Feedback uit werkgroepsessie 1: voor het object [SpeelEnSportVoorziening](http://test.data.vlaanderen.be/doc/applicatieprofiel/openbaardomein#SpeelEnSportVoorziening) kunnen als extra attributen voorzien worden:

- leeftijdsgroep
- merk

**Comment by tibaert** [comment]
Ook gezien bij use case (Provincie Oost-Vlaanderen): 
- Datum oplevering
- Datum garantie 
- Installatiedatum
- Aanschafwaarde 
- Toestelmerk
- Toestelmodel
- Afmetingen toestel 
- Leeftijdsgroep (min-max)
- ... 
Tevens probleem beheerder/eigenaar  #79

**Comment by tibaert** [comment]
Te bespreken tijdens diepteoverleg Taxonomie Infrastructuur. 
Ook kijken naar attributen die eerder generiek kunnen zijn.

**Comment by jensscheerlinck** [comment]
Momenteel out-of-scope voor het model Openbaar Domein.
Kan een lokale uitbreiding worden en indien hier vraag naar is kan dit later een eigen uitbreiding vormen binnen het OSLO Openbaar Domein model.
