### ISSUE TITLE
Extra object Bushok?

### ISSUE THREAD

**Issue by jensscheerlinck** [Informatievlaanderen/OSLO-Public-Discussion#85]
Zou als extra object in het model passen onder "BeheerElement > InfrastructuurElement > [StraatMeubilair](http://test.data.vlaanderen.be/doc/applicatieprofiel/openbaardomein#StraatMeubilair)"

Extra vragen:

- Een bushok bevindt zich op het openbaar domein maar is eigendom van De Lijn?
- Op een bushok worden ook vaak reclameborden bevestigd, hiervoor bestaat wel reeds een object in het model.

**Comment by annetom** [comment]
bushok zit al in het GRB, wegaanhorigheid, tpc=1

**Comment by jensscheerlinck** [comment]
GRB skeletbestek: 

https://www.agiv.be/producten/grb/objectcatalogus/componenten/grb-basis/wga1-bushok

Definitie:
> Een bushok biedt in de regel onderdak aan reizigers van het openbaar vervoer

**Comment by tibaert** [comment]
Te bespreken tijdens diepteoverleg Taxonomie Infrastructuur

**Comment by jensscheerlinck** [comment]
Zie: http://data.vlaanderen.be/doc/applicatieprofiel/infrastructuurcataloog/#Bushok
