### ISSUE TITLE
Extra object of attribuut nodig voor aanduiding plaatsen voor fietsdelen?

### ISSUE THREAD

**Issue by jensscheerlinck** [Informatievlaanderen/OSLO-Public-Discussion#86]
Momenteel wordt in het model onder "BeheerElement > InfrastructuurElement > [StraatMeubilair](http://test.data.vlaanderen.be/doc/applicatieprofiel/openbaardomein#StraatMeubilair)" reeds een type "[fietsstandplaats niet overdekt](http://test.data.vlaanderen.be/doc/applicatieprofiel/openbaardomein#StraatMeubilairTypeValue%3AFIETSSTANDPLAATS_NIET%20OVERDEKT)" voorzien.

Moet er een apart type (of apart attribuut) komen om aan te duiden of het om een standplaats specifiek voor fietsdelen gaat?

**Comment by tibaert** [comment]
Te bespreken tijdens diepteoverleg Taxonomie Infrastructuur

**Comment by jensscheerlinck** [comment]
Toegevoegd:

http://data.vlaanderen.be/ns/infrastructuur#fietsdelen

Alsook:

http://data.vlaanderen.be/ns/terreindeel#autodelen
