### ISSUE TITLE
Toevoegen van z-coördinaten aan objecten

### ISSUE THREAD

**Issue by jensscheerlinck** [Informatievlaanderen/OSLO-Public-Discussion#87]
Toevoeging z-coördinaat aan objecten in functie van overstroming, zichtbaarheid, ...

Standaard als attribuut bij elk object [BeheerObject](http://test.data.vlaanderen.be/doc/applicatieprofiel/openbaardomein#BeheerObject) toevoegen?

Wat wordt precies bedoeld met de z-coördinaat?

- Oppervlaktemodel (DSM)
- Terreinmodel (DTM)

Meer info: https://overheid.vlaanderen.be/DHM-Ondersteuning

**Comment by filipmahieu** [comment]
Nagaan bruikbaarheid van die data dan in Autocad. Data is data, maar Gis-data wordt nu nog te weinig rechtstreeks in Autocad gebruikt. Als men de GRB-(OSLO)-data ook in Autocad (met 3D-functionaliteit) zou kunnen gebruiken, is men weer een stuk vooruit.
'Z-coördinaat' bij lijnen en vlakken? Daar is meer voor nodig dan een numeriek veld...

**Comment by tibaert** [comment]
Wordt niet opgenomen binnen het Gegevensmodel Openbaar Domein.
