### ISSUE TITLE
Voorzien van metadata attributen rond methode/kwaliteit intekening

### ISSUE THREAD

**Issue by jensscheerlinck** [Informatievlaanderen/OSLO-Public-Discussion#88]
Feedback van werkgroepsessie 1:

Metadata attributen toevoegen aan het model om informatie te capteren met betrekking tot:
- Beeldkwaliteit in geval van intekening aan de hand van luchtfoto's
- Gebruikte methode/techniek voor intekening

Voorstel om dit toe te voegen als complex datatype op niveau van [BeheerObject](http://test.data.vlaanderen.be/doc/applicatieprofiel/openbaardomein#BeheerObject)

**Comment by filipmahieu** [comment]
Zou het algemeen houden op 'Gebruikte methode/techniek voor intekening'.  Soorten 'Luchtfoto', 'Op locatie met smartphone/tablet', 'Op locatie met handheld', 'Op locatie met totaalstation'.

**Comment by jensscheerlinck** [comment]
Attribuut "nauwkeurigheid" toegevoegd.
Definitie:

> De nauwkeurigheid waarmee objecten opgemeten worden hangt af van de meetmethode (terrestrisch of via luchtfotogrammetrie) en van de precisie waarmee objecten op het terrein kunnen aangeduid worden. Het GRB definieert 6 nauwkeurigheidsklassen van A tot en met F. Daarnaast werden op basis van het IMKL datamodel ook nog de waarden 'tot 50cm' en tot 100cm' opgenomen.

Nauwkeurigheidsklassen overgenomen uit het GRB, en aangevuld met twee (minder nauwkeurige) niveau's uit IMKL.

https://test.data.vlaanderen.be/doc/conceptscheme/Nauwkeurigsheidsklassen
