### ISSUE TITLE
Toevoegen extra attributen voor vegetatie elementen

### ISSUE THREAD

**Issue by jensscheerlinck** [Informatievlaanderen/OSLO-Public-Discussion#90]
Op niveau van [VegetatieElement](http://test.data.vlaanderen.be/doc/applicatieprofiel/openbaardomein#VegetatieElement) kunnen een aantal generieke attributen worden toegevoegd, waarvan sommige momenteel enkel voor [BoomVorm](http://test.data.vlaanderen.be/doc/applicatieprofiel/openbaardomein#BoomVorm) gedefinieerd zijn.

- Soort (nl & wetenschappelijk) 
- Belangrijk voor biodiversiteit?
- Beheersinformatie (welke soort wanneer onderhouden?) 

Voorstel om 1 attribuut "soort" te voorzien bij [VegetatieElement](http://test.data.vlaanderen.be/doc/applicatieprofiel/openbaardomein#VegetatieElement) en aanvullend een taxonomie te voorzien voor Soort met de volgende attributen/eigenschappen:
- soortnaam nl
- soortnaam wetenschappelijk
- belangrijk voor biodiversiteit?
- beheersinformatie

Reden: deze attributen zijn niet specifiek voor 1 object, maar gelden voor alle objecten die tot een bepaalde soort behoren. Bijgevolg niet nodig om deze op object niveau te gaan bijhouden (enkel soort volstaat).

**Comment by filipmahieu** [comment]
- Beheersinformatie 
 (welke soort wanneer onderhouden) moet op andere plaats, dit is al effectief bij het beheer. Want bv als de boom in een straat staat zal die anders moeten onderhouden worden dan in het bos.

- Eigenschap 'Te bestrijden volgens EU-lijst invasieve exoten' (exacte omschrijving zie INBO) erbij
- Ter info: ook ANB gebruikt een specifieke code (waarschijnlijk door ANB uitgevonden, gekend bij Vlaamse Natuur- en bosbeheerders) voor iedere soort boom, overleg met hen is welkom.  Kan als bijkomend attribuut ter koppeling databanken

**Comment by tibaert** [comment]
Soort toevoegen bij elk vegetatie-element. 
Meerdere soorten kunnen toevoegen voor hetzelfde object (array)
Soortnaam als codelijst vanuit een bron (nog consensus nodig welke bron) 
- GBIF: https://www.gbif.org/
- VVOG: http://www.vvog.info/soortwaarde_boomsoorten.asp
- EU-lijst invasieve exoten (exacte omschrijving zie INBO) #94

**Comment by tibaert** [comment]
Keuze voor GBIF vanuit diepteoverleg Boomvorm en Vegetatie-element en geïmplementeerd op niveau Vegetatie-element
