### ISSUE TITLE
TerreinDeelType voor Boomplantplaats

### ISSUE THREAD

**Issue by jensscheerlinck** [Informatievlaanderen/OSLO-Public-Discussion#91]
Voorstel uit werkgroepsessie 1 om aan [type](http://test.data.vlaanderen.be/doc/applicatieprofiel/openbaardomein#TerreinDeelTypeValue) van [TerreinDeel](http://test.data.vlaanderen.be/doc/applicatieprofiel/openbaardomein#TerreinDeel) "Boomplantplaats" te voorzien als potientiële plaats voor vegetatie.

**Comment by tibaert** [comment]
Definitie: De gereserveerde wortelzone, een ruimte (ondergronds) waar de wortels van bomen vrij kunnen groeien.

Nood aan een extra type “gereserveerde wortelzone” in de codelijst voor het type terreindeel. Bijgevolg zouden ook de attributen “wortelzoneDiepte” en “wortelzoneStraal” bij het object “Boomvorm” verwijderd mogen worden.

**Comment by tibaert** [comment]
Te bespreken tijdens diepteoverleg Terreindeel

**Comment by jensscheerlinck** [comment]
Toegevoegd: https://test.data.vlaanderen.be/doc/applicatieprofiel/terreindeel/#Boomplantplaats
