### ISSUE TITLE
Extra attributen voor Watervlak

### ISSUE THREAD

**Issue by jensscheerlinck** [Informatievlaanderen/OSLO-Public-Discussion#92]
Voorstel uit werkgroepsessie 1 om volgende attributen te voorzien voor object [Watervlak](http://test.data.vlaanderen.be/doc/applicatieprofiel/openbaardomein#Watervlak):

- silstaand of stromend? 
- anaerobisch?
- fauna?

**Comment by filipmahieu** [comment]
In de definitie staat 'stilstaand'.. Afstemmen met GRB-objecten Gracht (WGR) en Watergang (WTZ). 
Attributen 'anaerobisch' en 'fauna' zijn misschien te kort levend. Zaken kunnen door bv sanering plots veranderen.

**Comment by tibaert** [comment]
Consensus binnen WGS02: Attributen niet voorzien
