### ISSUE TITLE
Level of detail in OSLO openbaar domein

### ISSUE THREAD

**Issue by bogaerpe** [Informatievlaanderen/OSLO-Public-Discussion#93]
Om het GGINO verhaal werkbaar te houden voor alle steden en gemeenten is er meer nodig dan een oplijsting van objecten en hun attributen.
De ene gemeente wil gedetailleerder gaan, de andere heeft de middelen hiervoor niet.

Een oplossing zou er in kunnen bestaan om het begrip 'level of detail' in te voeren bij zowel geometrieën, objecten als attributen.

Ik verduidelijk
Voor attributen kan het opgelost worden door sommige attributen verplicht te maken, andere voidable
vb. Een boom kan een nederlandstalige naam hebben (verplicht) en een latijnse meer specifieke naam (niet-verplicht)
Voor objecten zou er met containerelementen gewerkt kunnen worden. 
vb. rijbaan als container is een containerbegrip en verplicht. De container rijbaan kan verder elementen bevatten zoals (boordsteen, straatgoot, parkeerstrook, middenberm, fietsstrook, ...) die niet verplicht zijn afhankelijk van een graad van detail die men wil bekomen.
Voor geometrieën kan men de generaliseren naar mate men minder detail wenst om de ligging van een object te beschrijven.
vb. Een zitbank als polygoon (niet-verplicht LOD2, geeft de oppervlakte aan die de zitbank inneemt), een zitbank als lijn (niet-verplicht LOD1, geeft aan in welke richting de zitbank geplaatst is), een zitbank als punt (verplicht LOD0), geeft de locatie van de zitbank weer. 
Van de polygoon kan men altijd terug generaliseren naar een lijn of een punt.

# TW-Openbaar Domein

**Comment by tibaert** [comment]
LOD bij attributen zit vervat in de kardinaliteit. In principe is het een Generiek Gegevensmodel waar de meeste attribuutinformatie vervat zit in andere databanken en is er het RelatieObject om te linken naar de desbetreffende databank. 

LOD bij objecten is afhankelijk in welke mate je organisaties wilt verplichten objecten te inventariseren. Het gegevensmodel legt op wat je op z'n minst van een object moet inventariseren indien je het inventariseert. 

LOD bij geometrieën een mogelijkheid. Kan bij [BeheerElement](http://test.data.vlaanderen.be/doc/applicatieprofiel/openbaardomein#BeheerElement): het attribuut "geometrie" (en eventueel "geometrieType"). Bij de individuele objectklassen een attribuut "minimumLOD" waar nu het attribuut "geometrie" is.

**Comment by filipmahieu** [comment]
Attributen

Verplicht stellen van attributen zal sowieso laag moeten zijn. Je mag al blij zijn als een (kleine) gemeente effectief begint te inventariseren en bv weet waar de te onderhouden bomen op hun grondgebied staan. Aan hen om het level of detail te definiëren.

**Comment by JorisVerbeken** [comment]
Misschien niet helemaal on topic hier, maar volgens onze ervaringen met GGINO in Aalst hebben we in versie 1.2 wel enkele "algemene" items aan de codelijst toegevoegd. Bijvoorbeeld bij "BestratingVerhardingTypeValue" hebben we "BESTRATING_VERHARDING_ALGEMEEN" gedefinieerd (definitie: Verhardingstype opgebouwd uit bestratingen (rechthoekige of vierkante componenten) waardoor een aanzienlijk aantal voegen tussen de componenten zitten.) (NOTE Algemeen attribuut dat kan gekozen worden wanneer geen verder detailniveau gewenst is. )
--> dit om de mogelijkheid te bieden niet in detail te moeten kiezen.

**Comment by tibaert** [comment]
Opgelost door vrije LOD Geometrie toe te voegen
LOD op object-niveau via taxonomie
