### ISSUE TITLE
Exotenbeheer

### ISSUE THREAD

**Issue by tibaert** [Informatievlaanderen/OSLO-Public-Discussion#94]
Het rapporteren van exoten is een Europese verplichting die voor Vlaanderen berust op bij het [INBO (exotenbeheer)](https://www.inbo.be/nl/thema/beheer/exoten). 
Gegevensmodel afstemmen met de huidige afgesproken systematiek (GBIF-code ...)

**Comment by tibaert** [comment]
Exoten zoals bij boomsoort (#90) niet als apart attribuut bijhouden per [VegetatieElement](http://test.data.vlaanderen.be/doc/applicatieprofiel/openbaardomein#VegetatieElement). Informatie over exoten zit binnen een soort (#90) en worden bijgehouden door het INBO: RelatieObject.

**Comment by filipmahieu** [comment]
Hierbij de lijst van exotensoorten zoals INBO ons doorgeeft. Je ziet de verschillende velden. Als je de GBIF-pagina van een soort wil vinden is de link http://www.gbif.org/species/[GbifAcceptedKey], bv [https://www.gbif.org/species/3034825](https://www.gbif.org/species/3034825) voor reuzenbereklauw.
Voor niet-exoten (bv bomen) is niet altijd een GBIF-code te vinden. Maar deze zou waar mogelijk steeds in de lijst van de lokale inventarisator/beheerder moeten zitten en bij uitwisseling worden meegegeven. 
[EU List_gbifcodes_NLnamen20180207.xlsx](https://github.com/Informatievlaanderen/OSLO-Public-Discussion/files/1724739/EU.List_gbifcodes_NLnamen20180207.xlsx)

**Comment by tibaert** [comment]
Zie diepteoverleg Vegetatie-Element en Boomvorm tussen WGS02 en WGS03
Keuze voor GBIF opgenomen.
