### ISSUE TITLE
Deksel - GRB-skeletbestek

### ISSUE THREAD

**Issue by tibaert** [Informatievlaanderen/OSLO-Public-Discussion#97]
Definitie [Putdeksel](https://www.agiv.be/producten/grb/objectcatalogus/entiteiten/wri-putdeksel) GRB: 

> Een putdeksel (Wri) is een deksel of luik van ondergrondse leidingen en installaties.

Is opgesplitst in: 

- [Cirkelvormig putdeksel (Wri1)](https://www.agiv.be/producten/grb/objectcatalogus/entiteiten/wri-putdeksel/cirkelvormig-putdeksel) en binnen het skeletbestek als [Zichtbaar cirkelvormig putdeksel (WRI1)](https://www.agiv.be/producten/grb/objectcatalogus/componenten/grb-basis/wri1-cirkelvormig-putdeksel)
- [Vierkant putdeksel (Wri2)](https://www.agiv.be/producten/grb/objectcatalogus/entiteiten/wri-putdeksel/vierkant-putdeksel) en binnen het skeletbestek als [Zichtbaar vierkant putdeksel (WRI2)](https://www.agiv.be/producten/grb/objectcatalogus/componenten/grb-basis/wri2-vierkant-putdeksel)

Met de belangrijkste kenmerken: 
- cirkelvormig (vrij) deksel met diameter gelegen tussen 65 en 100cm
- vierkante (vrije) deksels (65cm <= zijde <= 100cm)
- De hoogteligging van elk putdeksel (Wri) wordt steeds meegegeven (zie attribuut "Hoogte").
- De meetmethode van elk putdeksel (Wri) wordt steeds meegegeven (zie attribuut "Meetmethode").
- Het putdeksel (Wri) wordt aangemeten in het centrum van het luik of deksel.

**Comment by annetom** [comment]
ook hier heb je nog kleinere en grotere deksels beschreven in de aanvulling detail

**Comment by tibaert** [comment]
- [DekselTypeValue](http://test.data.vlaanderen.be/doc/applicatieprofiel/openbaardomein#DekselTypeValue) - [ZICHTBAAR_DEKSEL](http://test.data.vlaanderen.be/doc/applicatieprofiel/openbaardomein#DekselTypeValue%3AZICHTBAAR_DEKSEL): KNW18 Zichtbaar deksel of luik (Een zichtbaar deksel of luik is een merkteken dat zich in het vlak van de wegbaan bevindt. Alle deksels en luiken van ondergrondse leidingen en installaties, die een openbaar karakter hebben. Zijde of diameter groter dan 1,00m)
- [DekselTypeValue](http://test.data.vlaanderen.be/doc/applicatieprofiel/openbaardomein#DekselTypeValue) - [STRAATKAP](http://test.data.vlaanderen.be/doc/applicatieprofiel/openbaardomein#DekselTypeValue%3ASTRAATKAP): 
  - WPI17 - Zichtbare straatkap gelijkgronds (elke straatkap of deksel in beton, pvc, polyester of gietijzer die een leiding aanduidt. Een zichtbare straatkap gelijkgronds is een merkteken of deksel dat zich in het vlak van de wegbaan bevindt (bv. luiken en deksels communicatieleidingen, waterleiding ...). 
WPI702 tem WPI707: water, gas, elektriciteit, telefoon, brandkraan, divers. 
In gegevensmodel Openbaar Domein bij [DekselFunctieTypeValue](http://test.data.vlaanderen.be/doc/applicatieprofiel/openbaardomein#DekselFunctieTypeValue) nog RWA, DWA, EIGENDOM_WATERMAATSCHAPPIJ
  - WPI18 - Zichtbare straatkap bovengronds (Elke straatkap die een ondergrondse water- of gasleiding aanduidt. Een zichtbare straatkap bovengronds is een merkteken dat zich niet in het vlak van de wegbaan bevindt, bijvoorbeeld een luchtbaken, paaltjes TMVW ...) 
- [DekselTypeValue](http://test.data.vlaanderen.be/doc/applicatieprofiel/openbaardomein#DekselTypeValue) - [HUISAANSLUITING](http://test.data.vlaanderen.be/doc/applicatieprofiel/openbaardomein#DekselTypeValue%3AHUISAANSLUITING): WPI22 Huisaansluiting (Zichtbaar en publiek eindpunt van een huisaansluiting voor afval- en regenwater) 
- [DekselTypeValue](http://test.data.vlaanderen.be/doc/applicatieprofiel/openbaardomein#DekselTypeValue) - [PARTICULIER_DEKSEL](http://test.data.vlaanderen.be/doc/applicatieprofiel/openbaardomein#DekselTypeValue%3APARTICULIER_DEKSEL): WPI19 Particulier deksel (Deksels en luiken gelegen op private eigendom, zoals deksel van de ondergrondse brandstoftank, regen- en oppervlaktewaterput, septische put ... Hieronder vallen niet de riooldeksels.
