### ISSUE TITLE
Paal - GRB-skeletbestek

### ISSUE THREAD

**Issue by tibaert** [Informatievlaanderen/OSLO-Public-Discussion#98]
Definitie [Paal](https://www.agiv.be/producten/grb/objectcatalogus/entiteiten/wpi-puntvormige-inrichting/paal) binnen het GRB: 

> Palen behorende bij de [wegbaan (Wbn)](https://www.agiv.be/producten/grb/objectcatalogus/entiteiten/wbn-wegbaan), waarvan het contact met het grondoppervlak onvoldoende groot is om hen als lijn, veelhoek of cirkel te karteren.

Onder paal worden de volgende subcategorieën gegeven: 
WPI102 tem WPI111: Verlichting; elektriciteit; telefoon; bovenleiding tram, trein of trolley; seininstallatie overgang spoorbedding NMBS; verkeerslicht; verkeerslicht overhangend; verkeerslicht voetganger/fietser; flitspaal; divers 

Ten opzichte van [Paal](http://test.data.vlaanderen.be/doc/applicatieprofiel/openbaardomein#Paal) binnen het gegevensmodel Openbaar Domein: 

> Langwerpig verticaal (of eventueel enigszins schuin) geplaatst object, waarbij de breedte over de hele lengte ongeveer gelijk is."

Binnen het GRB-skeletbestek zijn andere constructies die betrekking hebben tot WPIx. Onder andere: 
- [Meerpaal (WPI3)](https://www.agiv.be/producten/grb/objectcatalogus/componenten/grb-basis/wpi3-meerpaal): Een paal/bolder, gelegen aan de rand van grote waterpartijen en van een speciale vorm voorzien om een schip vast te kunnen leggen bij het aanmeren. Een meerpaal is in principe hetzelfde als een bolder.
- [Bovengrondse brandkraan (WPI4)](https://www.agiv.be/producten/grb/objectcatalogus/componenten/grb-basis/wpi4-bovengrondse-brandkraan): Bovengronds aansluitingspunt aan de waterleiding, gelegen boven het maaiveld waar brandslangen op aangesloten kunnen worden. 
- [Grenspaal (WPI5)](https://www.agiv.be/producten/grb/objectcatalogus/componenten/grb-basis/wpi5-grenspaal): Een merkpaal die de grens van de Belgische Staat, de provincies en de gemeenten aanduidt. 
- [Communicatiepaal (WPI6)](https://www.agiv.be/producten/grb/objectcatalogus/componenten/grb-basis/wpi6-communicatiepaal): Een communicatiepaal is een paal met telefoon langs de openbare weg: 1. een praatpaal 2. een paal waarop een publieke telefoon is gemonteerd. 
- ...

**Comment by annetom** [comment]
Tim: binnen de GRB-skeletbestekken heb je nog veel andere types palen. Nu heb je enkel deze uit de GRB-basis mee, maar bv in de aanvulling detail heb je ook nog vlaggenmasten, palen waar wegwijzers, verkeersborden etc aan vast gemaakt zijn.

**Comment by tibaert** [comment]
Inderdaad. Een volledige oplijsting zou hier te ver leiden. Vele objecten binnen WPIx zitten vervat binnen [Installatie](http://test.data.vlaanderen.be/doc/applicatieprofiel/openbaardomein#Installatie) of [StraatMeubilair](http://test.data.vlaanderen.be/doc/applicatieprofiel/openbaardomein#StraatMeubilair). Belangrijk is om te zien hoe we de verscheidene objecten gaan categoriseren. 

[PaalTypeValue](http://test.data.vlaanderen.be/doc/applicatieprofiel/openbaardomein#PaalTypeValue)
- COMMUNICATIEMAST_DIVERS - KNW15 Communicatiemast divers (Een communicatiemast divers is een meervoudige metalen constructie zoals een tijdelijke GSM-mast, een mast van een radio-amateur, een private ontvangst- en zendinstallatie. 
- KNIPPERLICHT - WPI33 Knipperlicht (Een knipperlicht is een oranje, wit of rood knipperlicht op een paal, dat dienst doet als verkeerssignaal op wegen (vb. zone 30).)
- OPENBARE_STRAATVERLICHTING_AAN_GEVEL_OF_MUUR - WPI31 Openbare straatverlichting aan gevel/muur (Een openbare lichtpunt dat is bevestigd aan de gevel van een gebouw of constructie of bevestigd is aan een muur en dat gebruikt wordt om de omgeving te verlichten.) 
- PAAL_BOVENLEIDING_TRAM_TREIN_TROLLEY - [WPI1 Paal](https://www.agiv.be/producten/grb/objectcatalogus/componenten/grb-basis/wpi1-paal) - WPI105
- PAAL_ELEKTRICITEIT - [WPI1 Paal](https://www.agiv.be/producten/grb/objectcatalogus/componenten/grb-basis/wpi1-paal) - WPI103
- PAAL_SEINSINSTALLATIE_OVERGANG_SPOORBEDDING - [WPI1 Paal](https://www.agiv.be/producten/grb/objectcatalogus/componenten/grb-basis/wpi1-paal) - WPI106
- PAAL_TELEFOON - [WPI1 Paal](https://www.agiv.be/producten/grb/objectcatalogus/componenten/grb-basis/wpi1-paal) - WPI104
- PAAL_VERLICHTING - [WPI1 Paal](https://www.agiv.be/producten/grb/objectcatalogus/componenten/grb-basis/wpi1-paal) - WPI102
- VERKEERSLICHT - [WPI1 Paal](https://www.agiv.be/producten/grb/objectcatalogus/componenten/grb-basis/wpi1-paal) - WPI107
- VERKEERSLICHT_OVERHANGEND - [WPI1 Paal](https://www.agiv.be/producten/grb/objectcatalogus/componenten/grb-basis/wpi1-paal) - WPI08
- VERKEERSLICHT_VOETGANGER_FIETSER - [WPI1 Paal](https://www.agiv.be/producten/grb/objectcatalogus/componenten/grb-basis/wpi1-paal) - WPI109

**Comment by JorisVerbeken** [comment]
Volgens ervaring GGINO-vervolgtraject Aalst (GGINO 1.1 en 1.2): het prefix "PAAL_" bij PAAL_BOVENLEIDING_TRAM_TREIN_TROLLEY", "PAAL_ELEKTRICITEIT" PAAL_SEINSINSTALLATIE_OVERGANG_SPOORBEDDING", enz. zou weg mogen wegens niet relevant. IN GGINO 1.2 hebben we dit ook nog steeds zo staan, maar heeft eigenlijk geen meerwaarde.
