### ISSUE TITLE
Naamgeving "Beheer"

### ISSUE THREAD

**Issue by tibaert** [Informatievlaanderen/OSLO-Public-Discussion#99]
De benaming van [BeheerObject](http://test.data.vlaanderen.be/doc/applicatieprofiel/openbaardomein#BeheerObject), [BeheerElement](http://test.data.vlaanderen.be/doc/applicatieprofiel/openbaardomein#BeheerElement), [BeheerDeel](http://test.data.vlaanderen.be/doc/applicatieprofiel/openbaardomein#BeheerDeel), [BeheerGebied](http://test.data.vlaanderen.be/doc/applicatieprofiel/openbaardomein#BeheerGebied) is te specifiek gericht naar "Beheer". Andere benaming(en) voor deze generieke termen?

**Comment by tibaert** [comment]
Te bespreken tijdens diepteoverleg Beheergebied

**Comment by jensscheerlinck** [comment]
Aangepaste in nieuwste iteratie op basis van overleg met werkgroep (beheer weggelaten in benaming): http://data.vlaanderen.be/doc/applicatieprofiel/openbaardomein
